### ISSUE TITLE
Connection Status

### ISSUE THREAD

**Issue by minimok** [Automattic/monk#10]
Is there any way to know if a call like:

var db = monk('myURL')

actually opened a connection or not?

e.g. if my Mongo instance is down, I'd like to know about it. 

There doesn't seem to be any kind of 'connection' object,  Better would be something like:

var db = monk('myURL')
db.on('success')...
db.on('err')....

**Comment by otherwhitefrank** [comment]
+1

**Comment by carloscarcamo** [comment]
+1
