### ISSUE TITLE
event emitters not firing (mongo 3.0?)

### ISSUE THREAD

**Issue by dcsan** [Automattic/monk#101]
I'm using mongo/monk to try and get promises to reduce some CB ugliness but it seems to be creating more unusual problems to debug ("now you have two problems").

based off: https://gentlenode.com/journal/node-4-monk-cheatsheet/45

but I can't get promises or callbacks to respond.

am i doing this wrong or is there a problem with mongodb 3.0 / monk ?

I have a little routine to clear a collection and insert some data, however the on.complete or on.success isn't firing:

```typescript

    QuizPlugin.collection.remove({}, function(err, doc) {
        Clog.log("QP", "removed"); // get this
        var raw = FileReader.readDataFile(jsonfile);
        var that = this;
        raw.records.map(item => {
            var p = QuizPlugin.collection.insert(item.fields);
            console.log("p.type", p.type);
            p.on("success", function(doc) {
                console.log("done", doc) // never
            });
            p.on("complete", function(doc) {
                console.log("done", doc) // not this one either
            });
            p.on("error", function() {
                console.log("error")  // or this ever show up
            });

            // this method also doesn't emit anything
            // QuizPlugin.collection.insert(item.fields, function(err, doc) {
            //  console.log("inserted")
            // });
            // Clog.log("inserted:", item.fields.question);
        })

    })

```

Is there some other reason the inner on("success") aren't firing? the docs seem pretty clear, if spartan https://github.com/Automattic/monk#promises

could this be an issue with mongodb 3.0?
i upgraded when I couldn't get the above to work.

```bash
➜  bot1 git:(quiz) mongo --version
MongoDB shell version: 3.0.5

➜  bot1 git:(quiz) mongod --version
db version v3.0.5
git version: nogitversion

➜  bot1 git:(quiz) npm list monk
topicbot3@1.0.0 /Users/dc/dev/rikai/multibot/bot1
└── monk@1.0.1 
➜  bot1 git:(quiz) npm list  mongodb  
topicbot3@1.0.0 /Users/dc/dev/rikai/multibot/bot1
├── mongodb@2.0.42 
└─┬ monk@1.0.1
  └── mongodb@1.4.39 


# check no older versions globally installed:
➜  bot1 git:(quiz) npm list -g mongodb
/usr/local/lib
└── (empty)
➜  bot1 git:(quiz) npm list -g monk 
/usr/local/lib
└── (empty)


```

already [asked on stackoverflow](http://stackoverflow.com/questions/32264611/mongo-monk-not-firing-promise-done?noredirect=1#comment52417674_32264611) but it seems this maybe either a bug or an issue where the documentation is very confusing.

FWIW the data is getting written, just the callbacks aren't firing, so no way to know or handle it.

**Comment by travisjeffery** [comment]
can you put up a test repo on github reproducing the problem?

**Comment by dcsan** [comment]
thanks for your response. I did [put a repo together](https://github.com/dcsan/monk-test) to try and duplicate the issue, but with a simple repo the problem isn't there... must be some other combo of factors or modules. closing until i can repro.
