### ISSUE TITLE
Is it possible to use $where to expression condition: fieldA < fieldB in Monk?

### ISSUE THREAD

**Issue by hajimezhao** [Automattic/monk#102]
Hi Monk developer,
I am using nodejs+monk. Is it possible to use $where to expression condition: fieldA < fieldB in Monk?
I did Google many times but cannot find any clue about this feature in Monk.
Thank you very much! Have a nice day.
Best regards,
Khon

```javascript
			db.get('surveys').find(
			    {
				_id    : {$nin: alreadyAnswerSurveyIds},
				status : 'RUNING'
			    },
			    {
				limit  : 3,
				sort   : { dateCreated : 1 },
				// TODO it seems this line $where doesn't work
				$where : "fieldA < fieldB"
			    });
```

**Comment by alFReD-NSH** [comment]
I would suggest asking questions in stackoverflow and keep this issue tracker for bugs and feature requests. I'm not sure that's possible. But you can do this instead:

```
            db.get('surveys').find(
                {
                _id    : {$nin: alreadyAnswerSurveyIds},
                status : 'RUNING'
                fieldA: { $gt: 'fieldB' }
                },
                {
                limit  : 3,
                sort   : { dateCreated : 1 }
                });
```

**Comment by hajimezhao** [comment]
Hi alFReD-NSH,
Thank you very much! The second code works in my case. :dancers: 
But I wonder why the monk syntax is slightly different from MongoDB documentation  :(

Have a nice day,
Bests,
Khon

{code}
            db.get('surveys').find(
                {
                _id    : {$nin: alreadyAnswerSurveyIds},
                status : 'RUNING'
                $where: 'this.fieldA < this.fieldB'
                },
                {
                limit  : 3,
                sort   : { dateCreated : 1 }
                });
{code}
