### ISSUE TITLE
'.then(...).catch' not a function

### ISSUE THREAD

**Issue by oreqizer** [Automattic/monk#104]
Hi,

I just encountered this issue while working with promise queries. For example:

    users.find({})
      .then(data => {
        res.json(data);
      })
      .catch(err => {
        errors.db(err);
      });

works fine if only the `.then(...)` is present, but `catch` gets reported as not being a function.

**Comment by metame** [comment]
Replace `.catch(fn)` with `.error(fn)`.

**Comment by Oreqizer** [comment]
users.findOne({
    name: req.params.username
  })
  .then(data => {
    if (!data) {
      let err = new Error();
      err.status = 404;
      return next(err);
    }
    res.json(data);
  }, err => {
    next(err);
  });
//  .error(err => {
//    next(err);
//  });

This works. However, `.error(fn)` does not work, either for me - error gets replaced by `users.findOne(...).then(...).error is not a function`.

**Comment by lfilho** [comment]
i would also like to be able to use `.catch` since this is the standard on Javascript Promises.

**Comment by focusaurus** [comment]
More broadly, could monk get an update similar to mongoose to use ES6 promises when available and bluebird otherwise?

**Comment by tobei** [comment]
I really plus this, with es6 now being there and introducing Promise officially, would be great to get an update to monk so that it returns something promise friendly, or at least promise-compatible.

**Comment by alanstott** [comment]
+1

**Comment by mathieudutour** [comment]
fixed in #132 🎉
