### ISSUE TITLE
update return 1 even when the update fails

### ISSUE THREAD

**Issue by kebingyu** [Automattic/monk#106]
Unlike vanilla mongoDB, which returns something like { "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 }, monk's update simple returns 1 if update succeed or found match but fails the update. I am trying to use $addToSet in the update and I want to use the "nModified" to determine the next step. Am I missing some flag or this is built like this? Thanks!

**Comment by mathieudutour** [comment]
fixed in #132 🎉
