### ISSUE TITLE
Casting from hex to ObjectId returning hex

### ISSUE THREAD

**Issue by basickarl** [Automattic/monk#109]
```
To cast to ObjectId:
users.id('hexstring') // returns ObjectId
```

This does not return an ObjectId, but instead the string 'hexstring'

**Comment by metame** [comment]
The docs on the native Node.js MongoDb driver's [ObjectID.createFromHexString](https://mongodb.github.io/node-mongodb-native/api-bson-generated/objectid.html#objectid-createfromhexstring) gives some insight on the behavior of returning ObjectId from a hexstring.

To return an ObjectId using `users.id()` the argument entered must be a 12 byte binary string or 24 byte hexstring.

**Comment by basickarl** [comment]
@metame Must of made myself unclear. When I meant 'hexstring' I was meaning an actual hexstring. I do understand that I can create the ObjectID via that method through the link. 

However since monk already includes the driver, may I create it via monk in anyway? (Is there a way to access the native drive through monk?)

**Comment by metame** [comment]
@basickarl 
I looked into this further for my own understanding as well.  `users.id('hexstring')` does not change the string value representation but wraps it into an Object, specifically the BSON ObjectID type.  Then the ObjectID class methods, e.g. `toString()`, `valueOf()`, `getTimestamp()` are available.

Example:

    var hexstring = '686578737472696e67616161';    
    var objectIdFromHex = users.id(hexstring); // returns value of '686578737472696e67616161'
    typeof hexstring; // returns 'string'
    typeof objectIdFromHex; // returns 'object'
    objectIdFromHex.getTimestamp(); // returns formatted time stamp
    hexstring.getTimestamp(); // returns TypeError as does not inherit from ObjectID class

This native node driver 2.0 docs on [converting ObjectIDs into strings](http://docs.mongodb.org/manual/reference/object-id/#convert-objectids-into-strings) help explain this more clearly than the link in my previous post.

**Comment by mathieudutour** [comment]
A lot has changed in monk@2.0. I'm closing this issue, feel free to open a new one if it is still an issue.
