### ISSUE TITLE
could monk use a more recent version of mongoskin...

### ISSUE THREAD

**Issue by mrose17** [Automattic/monk#111]
... so we could get rid of the dreaded 

        { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
        js-bson: Failed to load c++ bson extension, using pure JS version

error found in `mongoskin 0.1.14`?

thanks!

/mtr

**Comment by travisjeffery** [comment]
Hmm yeah, lemme check

**Comment by mrose17** [comment]
groovy!

**Comment by travisjeffery** [comment]
Actually looks like there's gonna be some issues updating, plus at this point the mongo driver does pretty much everything mongoskin does so I'm gonna look into removing it this weekend.

**Comment by mrose17** [comment]
hi. thanks for looking into it. hopefully mongoskin can be OBE'd...

**Comment by j** [comment]
+1

**Comment by pballester** [comment]
+1

**Comment by dyngosz** [comment]
+1

**Comment by okalachev** [comment]
+1

**Comment by jgraham909** [comment]
FWIW I updated mongoskin to 2.0.3 and mongodb to 2.0.47 with monk 1.0.1 and it appears to be working fine.

**Comment by woozyking** [comment]
+1

**Comment by st3xupery** [comment]
+1

**Comment by basickarl** [comment]
+1

**Comment by ratson** [comment]
For those who can't wait, I released [monkii](https://www.npmjs.com/package/monkii) with mongoskin v2 support.

Feel free to try and [report issues](https://github.com/ratson/monkii/issues).

**Comment by vnglst** [comment]
+1

Using monkii right now...

**Comment by mathieudutour** [comment]
fixed in #132 🎉
