### ISSUE TITLE
can use dropIndex, dropIndexes on collection

### ISSUE THREAD

**Issue by Prozi** [Automattic/monk#113]
Grep your project for dropIndex
it's just in the documentation

Did someone forget to commit something? ;-)

**Comment by travisjeffery** [comment]
hm yep looks like it

**Comment by Prozi** [comment]
are there any chances it will be fixed anytime soon, this would be very helpful. Thanks!

**Comment by atheros** [comment]
This would be more than useful. Any chances there will be a fix?

**Comment by armchairdj** [comment]
Any progress on this?

```TypeError: Object #<Collection> has no method 'dropIndex'```

**Comment by Prozi** [comment]
What I did was look into some other function and create this function myself
from addIndex as far as i can remember, dont have the code atm
