### ISSUE TITLE
Breaks with newly released node 5.0.0?

### ISSUE THREAD

**Issue by shaharsol** [Automattic/monk#114]
One of the dependencies, mongoskin, seems to break it with node5.0.0. an excrept from the log file:

/app/node_modules/mongoskin/lib/utils.js:33
var skinClassName = 'Skin' + NativeClass.name;
^
TypeError: Cannot read property 'name' of undefined at makeSkinClass (/app/node_modules/mongoskin/lib/utils.js:33:43) at Object.<anonymous> (/app/node_modules/mongoskin/lib/grid.js:6:35) at Module._compile (module.js:425:26) at Object.Module._extensions..js (module.js:432:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:311:12) at Module.require (module.js:366:17) at require (module.js:385:17) at Object.<anonymous> (/app/node_modules/mongoskin/lib/db.js:22:16) at Module._compile (module.js:425:26) Exception

**Comment by tbrisbane** [comment]
Can confirm. Same issue.

**Comment by ebemunk** [comment]
I came across this issue as well. This is related to peerDependencies (mongodb@~1.4) that mongoskin uses, as per the new npm v3 update, the peerDependencies are no longer automatically installed.

The way I solved it was the make it (it being the package mongodb@~1.4) a dependency of my own package.

```
npm i mongodb@~1.4 --save
```

solved the issue for me.

**Comment by shaharsol** [comment]
But then I bind myself to that version of the package, right? what if I need mongodb2.x?

**Comment by ebemunk** [comment]
Well, if npm had installed the peer dependency it wouldn't have mattered, you would still get the same package. monk has a dependency on mongoskin@1.4.13 which has a dependency on mongodb@~1.4. In another issue (#111) there are talks about upgrading mongoskin to ~2 which will provide mongodb2.x

**Comment by basickarl** [comment]
@ebemunk mongodb@~1.4 worked for me ta!

**Comment by sevameyer** [comment]
@ebemunk thank you so much! Out all of the suggested solutions I found only yours actually solved the problem!

**Comment by shaddy123456** [comment]
Reverting to mongod@1.4 solvedthe problem for  me

**Comment by Russian60** [comment]
`npm i mongodb@~1.4 --save` works for me too! Thanks @ebemunk

**Comment by mathieudutour** [comment]
fixed in #132 🎉
