### ISSUE TITLE
Combining sort and limit not working

### ISSUE THREAD

**Issue by ghost** [Automattic/monk#118]
I'm not sure if this is a bug but I don't see any support forum or wiki so reporting it here.

I have this query that works in against vanilla MongoDB:

    db.getCollection('widgets').find({num_skus: 0}).sort({price: -1}).limit(5)

i.e. get the 5 highest priced widgets that have num_skus == 0. I get 5 results back.

In Monk I am trying:

    db.get('widgets').find({num_skus: 0}, {sort: {price: -1}, limit: 5}, function(e, docs) {
      // callback happens with docs undefined.
    });

and I get no results back.

Am I doing something wrong or is this a bug?

**Comment by geekraver** [comment]
Might be a dup of #107. If I look at the error it is the same (QueryFailure flag set on getmore command).

**Comment by bhs128** [comment]
I had a similar issue:

`{ [MongoError: QueryFailure flag set on getmore command] name: 'MongoError' }`

when using this query
```
db_collection.find({}, {"limit" : per_page, "skip": skip, "sort":{"created": -1}}, 
    function (db_err, db_docs) {
              .
              .
```
 I was able to fix it by creating an index on the collection. I assume for me it was related to this:

https://docs.mongodb.org/v3.0/reference/limits/#Sort-Operations

>Sort Operations
>If MongoDB cannot use an index to get documents in the requested sort order, the combined size of all documents in the sort operation, plus a small overhead, must be less than 32 megabytes.

**Comment by mathieudutour** [comment]
A lot has changed in monk@2.0. I'm closing this issue, feel free to open a new one if it is still an issue.
