### ISSUE TITLE
npm install monk --save fails on windows 10 professional 64bit

### ISSUE THREAD

**Issue by najamsk** [Automattic/monk#122]
KoaApps> npm install monk --save
npm WARN package.json TheFirstKoaApps@0.0.1 No repository field.
npm WARN peerDependencies The peer dependency mongodb@~1.4 included from mongoskin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> kerberos@0.0.11 install E:\Training_Hot\PluralSight Introduction to Koa Javascript\PluralSight Introduction to Koa Javascript\Exercise files\javascript-koa-introduction\1-javascript-koa-introduction-m1-exercise-files\demos\after\TheFirstKoaApps\node_modules\monk\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> bson@0.2.22 install E:\Training_Hot\PluralSight Introduction to Koa Javascript\PluralSight Introduction to Koa Javascript\Exercise files\javascript-koa-introduction\1-javascript-koa-introduction-m1-exercise-files\demos\after\TheFirstKoaApps\node_modules\monk\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm WARN optional dep failed, continuing kerberos@0.0.11
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "monk" "--save"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe

npm ERR! bson@0.2.22 install: `(node-gyp rebuild 2> builderror.log) || (exit 0)`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the bson@0.2.22 install script '(node-gyp rebuild 2> builderror.log) || (exit 0)'.
npm ERR! This is most likely a problem with the bson package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node-gyp rebuild 2> builderror.log) || (exit 0)
npm ERR! You can get their info via:
npm ERR!     npm owner ls bson
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Training_Hot\PluralSight Introduction to Koa Javascript\PluralSight Introduction to Koa Javascript\Exercise files\javascript-koa-introduction\1-javascript-koa-introduction-m1-exercise-files\demos\after\TheFirstKoaApps\npm-debug.log

**Comment by mathieudutour** [comment]
A lot has changed in monk@2.0. I'm closing this issue, feel free to open a new one if it is still an issue.
