### ISSUE TITLE
findAndModify not working

### ISSUE THREAD

**Issue by basickarl** [Automattic/monk#124]
Monk lacks documentation as to implement findAndModify in the following case:
```
            myCollection.col.findAndModify({
                query: {
                    token: myVar
                },
                remove: true,
                new: false
            }, function (err, res) {
                if (err)
                    throw err;
                console.log(JSON.stringify(res));
            });
```
Results in: `MongoError: need remove or update`

**Comment by robjens** [comment]
You may want to take a look at `mongoskin` for this one. I was about to post the same until I remembered `monk` is just a lean skin for mongoskin. Then I looked it up and according to SO this must be the signature:

`collection.findAndModify(query, sort, update, options, callback)`

**Comment by robjens** [comment]
I should add that `new` doesn't work either. It doesn't return the updated document.
