### ISSUE TITLE
Add proper error handling to insert query function in lib/collection.js:337

### ISSUE THREAD

**Issue by danielkalen** [Automattic/monk#126]
[lib/collection.js:337](https://github.com/Automattic/monk/blob/master/lib/collection.js#L337)

When there is an error such as an authentication error while calling this function, the app will throw on error when executing res=docs.ops[0] since docs is null.

**Comment by mathieudutour** [comment]
well no since we are checking if docs is not null https://github.com/Automattic/monk/blob/master/lib/collection.js#L340

**Comment by danielkalen** [comment]
Well this issue is no longer an issue since the few last previous commits... [This](https://github.com/Automattic/monk/blob/a89877066f6d3409d0e59d48d0378da2a9d62864/lib/collection.js#L323) is what I was complaining about before...

**Comment by mathieudutour** [comment]
alright, my bad ;)
