### ISSUE TITLE
Get results which is json of query directly instead of the results in a promise's callback

### ISSUE THREAD

**Issue by Xheldon** [Automattic/monk#129]
just like title said,how can i get the data from a query directly instead of deal with in a callback?
here are some code:
now:
     `$data.getContent(function(data){
        res.render('content',{
            article:data
        }))
    });`
the $data.getContent is:
`exports.getContent = function(fn){
    db.get('contentcollection').find().success(function(doc){
        fn(doc);
    });
}`

after:
`res.render('content',{
       article:$data.getContent()
  }))`

i try to return the 'doc' to 'getContent' directly:
`exports.getContent = function(fn){
    db.get('contentcollection').find().success(function(doc){
        return doc
    });
}`

but obvious it not work within a asyn callback

can you help me?

**Comment by mathieudutour** [comment]
Querying a database is always asynchronous, there is no way around it.
