### ISSUE TITLE
wrap non-$ fields in the `update` object in `$set`

### ISSUE THREAD

**Issue by mathieudutour** [Automattic/monk#145]
eg automatically transform

```
users.update({}, { name: 'Bob' })
```

to 

```
users.update({}, { $set: { name: 'Bob' } })
```

**Comment by JaKXz** [comment]
I think the better approach would be #150

**Comment by mathieudutour** [comment]
Fixed by using the https://github.com/monk-middlewares/monk-middleware-wrap-non-dollar-update middleware
