### ISSUE TITLE
Inserting field with `undefined` value inserts `null` instead of `undefined`

### ISSUE THREAD

**Issue by jedborovik** [Automattic/monk#146]
For example:

``` js
collection.insert({ name: undefined })
```

inserts `{ name: {} }` and not `{ name: undefined }`. I'm using monk 3.0.4.

The mongo shell inserts `{ name: undefined }` for same insert command.

**Comment by mathieudutour** [comment]
it's fixed in monk@3.0.6

**Comment by jedborovik** [comment]
Just tried with monk@3.0.6 and rather than inserting `{ name: undefined }`, it is inserting `{ name: null }`.

The nice thing about having `undefined` over `null` is ES6 default values only act on `undefined`, not `null`.

The benefit of `{ name: undefined }` is it allows something like:
```js
collection.findOne({ email: 'me@email.com' }).then(({ name = 'No name' }) => {
  // yadda yadda
});
```

**Comment by mathieudutour** [comment]
Indeed, it would be nice but the difference between `undefined` and `null` is not supported in the nodejs mongo driver (http://devblog.me/wtf-mongo part 2) (https://github.com/meteor/meteor/issues/1646#issuecomment-29682964)

I'll think about what we can do but I'm afraid it's not much

**Comment by mathieudutour** [comment]
maybe deleting the undefined fields on insert?

**Comment by jedborovik** [comment]
Yikes, I didn't realize the BSON spec deprecated `undefined`. 

Deleting the undefined fields on insert sounds like a great suggestion. That does seem to mimic the behavior of a javascript object more than having a null value.

**Comment by mathieudutour** [comment]
This can be implemented as a middleware (see https://automattic.github.io/monk/docs/middlewares.html) in user-land.

Will close this as it probably shouldn't be core

**Comment by jaredpalmer** [comment]
@mathieudutour can you show what the middleware would look like?

**Comment by mathieudutour** [comment]
hum maybe something like:
```js
module.exports = function (context) {
  return function (next) {
    return function (args, method) {
      if (!args.data) {
        return next(args, method)
      }

      if (typeof args.data !== 'object') {
        return next(args, method)
      }

      const dataWithoutUndefined = Object.keys(args.data).reduce((prev, k) => {
        if (typeof args.data[k] !== 'undefined') {
          prev[k] = args.data[k]
        }
        return prev
      }, {})

      args.data = dataWithoutUndefined
      return next(args, method)
    }
  }
}
```

**Comment by ceoworks** [comment]
it seems like mongo has connection option `ignoreUndefined`, which could solve this issue.
https://mongodb.github.io/node-mongodb-native/2.1/reference/connecting/connection-settings/
