### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by cyberjoac** [Automattic/monk#147]
Great work with the latest release of Monk !!

Still, is it possible to leave online the old documentation before we update ?
Also, does the new syntax support callback syntax or is it only with .then ?

Thanks a lot !

**Comment by mathieudutour** [comment]
it does support the callback syntaxt

**Comment by mathieudutour** [comment]
The old readme is still accessible here: https://github.com/Automattic/monk/tree/4b0114440d91d1c570b30c713c3f4613e4b5933d
