### ISSUE TITLE
Collection.update() return { ok: 1, nModified: 1, n: 1 } instead of a number

### ISSUE THREAD

**Issue by ericfong** [Automattic/monk#149]
Collection.update() 

return a object

{ ok: 1, nModified: 1, n: 1 }

instead of a number 1. 
It is expected behaviour?

**Comment by mathieudutour** [comment]
there are different information in this result:
 * `n` is the number of matched documents
 * `nModified` is the number of modified documents
 * `nUpserted` is the number of upserted documents (when using the `upsert` option)

Not sure which one to pick to return only a number

**Comment by ericfong** [comment]
As I remember old monk 1 just return the affected number (as I remember) of records. 

Surprise to find that become a object.

I think may be add that to change log to keep it like that.

 Thx

**Comment by mathieudutour** [comment]
just did: https://github.com/Automattic/monk/commit/3a94323846d3397e3408ac10575348bddaaeff8e

Also maybe instead of just saying "Return a promise" in the docs, we should say what the promise will resolve

**Comment by vikaschauhan1** [comment]
How can I return a raw response instead of {ok: 1, nModified: 0, n: 1}  in the callback using the update function ?

**Comment by lopugit** [comment]
can you get this to return the updated document like MongoDB's findoneandupdate callback functionality?

**Comment by lopugit** [comment]
all g you just gotta use findOneAndUpdate :')
