### ISSUE TITLE
DSL for building an aggregation pipeline

### ISSUE THREAD

**Issue by jgamedev** [Automattic/monk#150]
Hello wise JS monks,

I was trying monk the other day and I wanted to write an aggregation pipeline, so I thought I could type something like:

```
const pipe = new monk.pipeline()
.project(['author', 'tags'])
.unwind('tags')
.group('tags')
.addToSet('authors')

users.aggregate(pipe)
```

... which would save me from writing: 

```
users.aggregate([
  { $project : {
    author : 1,
    tags : 1
  }},
  { $unwind : "$tags" },
  { $group : {
    _id : {tags : "$tags"},
    authors : { $addToSet : "$author" }
  }}
])
```

But instead I learned that, being a "thin wrapper", monk expects me to type everything in Mongolian languages, which is justifiably not a bad thing!  :wink: 

However I'ḿ still curious to know if such a DSL has been discussed or maybe exists in another library or repository that guys know about?

Obviously with such a simple example, a DSL doesn't seem to be advantageous. However the more an aggregation definition grows in complexity, the longer it takes for someone new coming to the codebase to reason about it, and that's when a DSL would come in handy.

(P.S:  I created a whip of the implementation just for kicks: http://codepen.io/anon/pen/wWmEWk?editors=0011

**Comment by mathieudutour** [comment]
That's really nice! 
Not sure if it should be in the core though, but if you want to create a package for it, I'd be happy to link to it in the docs

**Comment by mathieudutour** [comment]
(you might want to look at this: https://github.com/rschmukler/maggregate btw)

**Comment by JaKXz** [comment]
I think exposing the `maggregate` API would be an excellent addition to monk! Keeps concerns separated in modules, is an optional enhancement, and is well documented from the glances I've taken.

**Comment by mathieudutour** [comment]
I don't think it should be core. Let's close this. Happy to link to a user-land package in the readme if you come up with a nice one
