### ISSUE TITLE
getting around ObjectId 24 hex character limitation

### ISSUE THREAD

**Issue by pocketmax** [Automattic/monk#156]
If I specify an _id field with a string value on an insert, I get an error if it exceeds the 24 hex char limit of an ObjectId. If I run the same insert directly at the mongo console, the insert goes through. Is there a way to override the ObjectId override on inserts so monk can insert docs with a custom _id that exceeds the 24 hex char maximum?

here is the query I used
```json
{
	"_id": "f2323r343434r34r34t34t45t343434r34r34r34r34r34r3434r34r888888888888889999999999999999999999999f2323r343434r34r34t34t45t343434r34r34r34r34r34r3434r34r888888888888889999999999999999999999999",
"foo": "bar"
}
```

**Comment by mathieudutour** [comment]
hum you can disable the ObjectId casting by using the option `{castIds: false}` as the second argument of the insert method but then it won't be an ObjectId (obviously).

When you do that in the mongo console, it's not storing an objectId neither. 

So yes, you can do it but use it at your own risks.
