### ISSUE TITLE
Example given in README.md doesn't work

### ISSUE THREAD

**Issue by maxhartshorn** [Automattic/monk#157]
Running the following example given in README.md, `controller.storage.teams.get('cool')` returns `null`

`var beans = {id: 'cool', beans: ['pinto', 'garbanzo']};
controller.storage.teams.save(beans);
beans = controller.storage.teams.get('cool');`

It looks like the underlying Monk api returns a promise, but that promise is not returned by the `get` function so we get `beans === null`.

How would people feel about changing `table.findOne({id: id}, cb);` to `return table.findOne({id: id}, cb);` in the `get` function and `table.find({}, cb);` to `return table.find({}, cb);` in the `all` function? This way plugin users can handle the promise themselves.

I realize there is a callback option, but it appears not to be called with any arguments, so I am unsure how else to retrieve data using this module.

**Comment by mathieudutour** [comment]
hum I'm not sure what you are talking about. What are the `get` and the `all` functions?

And `save` doesn't exist in monk

**Comment by maxhartshorn** [comment]
woah sorry wrong repo
