### ISSUE TITLE
collection.ensureIndex deprecated in MongoDB 3.0.0

### ISSUE THREAD

**Issue by axelpale** [Automattic/monk#161]
See [this mongoose issue](https://github.com/Automattic/mongoose/issues/3280) and [this reference](https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/). The method `ensureIndex` becomes alias with `createIndex` starting Mongo 3.0.0. Thus, I propose, `createIndex` should be added to Monk API.

**Comment by mathieudutour** [comment]
yeah, happy to accept a PR in this direction

**Comment by andela-abankole** [comment]
I think `ensureIndex` sounds fine, moreover mongodb driver uses `ensureIndex` http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#ensureIndex

**Comment by demsking** [comment]
Is there any chance to have a merge of #169 to master please?
