### ISSUE TITLE
Adding more mongo methods

### ISSUE THREAD

**Issue by ockang** [Automattic/monk#162]
hello, some api mongodb not work as updateMany among others, it would be good to apply some more

**Comment by mathieudutour** [comment]
you can set the `multi` option on the `update` method. 

I believe that a API should have the smallest surface possible so I'm reluctant to add methods just for the sake of adding methods. Which one do you think are really missing?

**Comment by mathieudutour** [comment]
I'm closing this as it is a bit too general. Let's open separate issues for each methods you would like to see in monk
