### ISSUE TITLE
Crash if _id is undefined in a model being saved

### ISSUE THREAD

**Issue by JoelParke** [Automattic/monk#165]
I discovered that if I called Collection.prototype.insert  with data which had data._id === 'undefined'  the call to
```
    util.cast(data)
```
caused a crash.  This is new behavior from long back, since I just upgraded to monk again.  The issue is seen in the cast code:

```
exports.cast = function cast (obj) {
  if (Array.isArray(obj)) {
    return obj.map(cast)
  }

  if (obj && typeof obj === 'object') {
    Object.keys(obj).forEach(function (k) {
      if (k === '_id') {
        if (obj._id.$in) {
          obj._id.$in = obj._id.$in.map(id)
        } else if (obj._id.$nin) {
          obj._id.$nin = obj._id.$nin.map(id)
        } else if (obj._id.$ne) {
          obj._id.$ne = id(obj._id.$ne)
        } else {
          obj._id = id(obj._id)
        }
      } else {
        obj[k] = cast(obj[k])
      }
    })
  }

  return obj
}
```
I resolved this by adding a check to the cast code to not do a map if `obj._id===undefined`.  
See ` if (k === '_id' && obj._id) ` below
```
exports.cast = function cast (obj) {
  if (Array.isArray(obj)) {
    return obj.map(cast)
  }

  if (obj && typeof obj === 'object') {
    Object.keys(obj).forEach(function (k) {
      if (k === '_id' && obj._id) {
        if (obj._id.$in) {
          obj._id.$in = obj._id.$in.map(id)
        } else if (obj._id.$nin) {
          obj._id.$nin = obj._id.$nin.map(id)
        } else if (obj._id.$ne) {
          obj._id.$ne = id(obj._id.$ne)
        } else {
          obj._id = id(obj._id)
        }
      } else {
        obj[k] = cast(obj[k])
      }
    })
  }

  return obj
}
```
I am also changing my application code so that _id will not be defined except by monk.  
Should I be setting the `opts.castIds=false` instead when it is saving a new model???

**Comment by mathieudutour** [comment]
I'm happy to accept a PR with your fix.

In the meantime, you can either not specify `_id` in the object you want to insert (which I'm not sure what's the use case to initialise it with `undefined`) or use `opts.castIds=false`

**Comment by JoelParke** [comment]
Did the pull request - but was not sure about fix comment standards.
