### ISSUE TITLE
Add mapReduce method

### ISSUE THREAD

**Issue by Hiskyprince** [Automattic/monk#167]

**Comment by andela-rekemezie** [comment]
@Hiskyprince, please can you provide more context as to the direction you're thinking of it. I would want to pick up this task.

**Comment by mathieudutour** [comment]
we are adding wrapper to mongodb methods, here is an the aggregate method: https://github.com/Automattic/monk/blob/master/lib/collection.js#L112

We are missing the `mapReduce` method. So you would need to define it in the file I just linked and write the tests for it. 

Thanks!

**Comment by IanSchweer** [comment]
Hey Guys, I started working on this: #181

**Comment by mathieudutour** [comment]
nice 👍  ping me when you have written the tests

**Comment by IanSchweer** [comment]
@mathieudutour added the unit tests and the travis checks are passing. The pr is #181
