### ISSUE TITLE
Are there any event handlers to deal with the "error-opening" event

### ISSUE THREAD

**Issue by rightm** [Automattic/monk#170]
mongodb : 2.1.18
monk version:3.1.2
when my mongo is down ,then i can not get anything .so i add a callback in Manager.prototype.then 
,i got the error below :
``
(node) warning: possible EventEmitter memory leak detected. 11 error-opening listeners added. Use ```

> emitter.setMaxListeners() to increase limit.
> Trace
>     at Manager.addListener (events.js:252:17)
>     at Manager.once (events.js:278:8)
>     at Manager.<anonymous> (E:\git\NatureCloud\node_modules\monk\lib\manager.js:175:10)
>     at Manager.then (E:\git\NatureCloud\node_modules\monk\lib\manager.js:173:10)
>     at storageMetaInfoDB.myMongoDB (E:\git\NatureCloud\db\mongodb.js:13:10)
>     at new storageMetaInfoDB (E:\git\NatureCloud\db\storageMetaInfoDB.js:12:10)
>     at Object.<anonymous> (E:\git\NatureCloud\lib\k8s\kubernetes.js:30:21)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)

```

 i hava to add a   callback function in Manager.prototype.then or  Manager.prototype.catch to get what happened ?

**Comment by mathieudutour** [comment]
It's just a warning, you can (based on the information you gave) safely ignore it.

What is happening?
When you start using monk, you usually don't wait for the connection to do queries:
```
const db = monk()

db.get('users').find()
```

Let's say we have 15 queries like this throughout the node app. Each of those queries will register an event listener to know when they will actually be able to query the database. Once the connection is opened (or closed), the event listeners are freed.

Does it answer your question or did I misunderstood?
