### ISSUE TITLE
Custom ID

### ISSUE THREAD

**Issue by minimok** [Automattic/monk#173]
mate, I have a collection of currencies - the only id that we're allowed in the '_id' field is a 3-letter string: e.g. USD, CAD, EUR etc

How the heck do you do this in mongo / monk? I need to create my object like: 

let myCurrency - {id: 'USD, countries: []}

Once I have a object like this, my expectation is that the monk library will store it for me. This is not happening...

It's safe to assume I've looked a the tests and got zero help from them...thx.

**Comment by minimok** [comment]
Cancel that...this is a breeze with the native driver...

**Comment by mathieudutour** [comment]
there is the option `castIds` that you can set to `false` (at the collection level possibly)
