### ISSUE TITLE
collection.index not working on MongoDB 3.4

### ISSUE THREAD

**Issue by itapel** [Automattic/monk#174]
When trying to create  / ensure index on MongoDB 3.4 
(sample code: 
var my_collection= db.get('my_collection_name');
my_collection.index({some_field_name:1}, function (err) {...});
)
I'm getting MongoError: The field 'fields' is not valid for an index specification.

The same code works on MongoDB 3.2

**Comment by eyalsach** [comment]
+1, would be great to get this fixed, otherwise need to use the underlying mongo driver
