### ISSUE TITLE
findOneAndUpdate & findOneAndDelete

### ISSUE THREAD

**Issue by elliotritchie** [Automattic/monk#175]
I just wanted to check that the `findOneAndUpdate` & `findOneAndDelete` behaviour was intentional. I expected it to be similar to `findOne` where if no document satisfies the query then null is returned but it looks like a Mongo `findAndModifyWriteOpResultObject` is returned instead. Should I be doing something like this in my callbacks?

```
if (doc.ok && doc.lastErrorObject) {
    // doc not found
} else {
    // doc found
}
```

Many Thanks

**Comment by mathieudutour** [comment]
You are right, it should probably return `null`
