### ISSUE TITLE
When to close database?

### ISSUE THREAD

**Issue by ArtworkAD** [Automattic/monk#176]
Hey guys,

I have an api module where I put all my api methods that need a db connection

`my_api.js:`

```
const database = require('monk')(process.env.DB_HOST + '/' + process.env.DB_NAME);
const components = database.get('components');

module.exports.list = async ctx => {
    ctx.body = await components.find({});
}

module.exports.get = ...
module.exports.create = ...
module.exports.update = ...
module.exports.delete = ...

```

My question is, where I am supposed to close the db connection? Is it more appropriate to have a single database connection for the entire app instance instead of creating it in each module?

**Comment by mathieudutour** [comment]
if you are running a server, ie a node process which is not supposed to stop, you don't need to close the connection.

And yes, it's probably best to share a db connection, it will be a lot faster.
