### ISSUE TITLE
deleteOne is not a function

### ISSUE THREAD

**Issue by syuilo** [Automattic/monk#178]
It exists in Mongodb-Native, but does not exist in monk?

http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#deleteOne

`Remove` has been deprecated and written to use `deleteOne` instead.
![image](https://cloud.githubusercontent.com/assets/4439005/22748444/73b51a96-ee6d-11e6-9b48-e89698e767ed.png)

Thanks for this great lib.

**Comment by mathieudutour** [comment]
Yes. But I really don't like the API of having 2 methods to do the same thing.

I think I'll modify the monk `remove` to use the mongo `deleteOne` and `deleteMany` depending on wether there is the option `multi` or `single`
