### ISSUE TITLE
Sort + limit fields

### ISSUE THREAD

**Issue by thierryskoda** [Automattic/monk#182]
Hey guys I'm trying to find all users and sort them by score and also only returning the score field for each users but it doesn't work. Am I doing something wrong? :(

`User.find({ active: true }, 'score', { sort: { score: -1 } })`

I also tried `User.find({ active: true }, 'score').sort({ score: -1 })` but I got `User.find(...).sort is not a function`

Thank you for any help!

**Comment by mathieudutour** [comment]
you can pass an object as the options:
```
User.find({ active: true }, {
   fields: { score : 1 },
   sort: { score: -1 }
})
```

**Comment by thierryskoda** [comment]
Oh thank you!
