### ISSUE TITLE
Release on Github

### ISSUE THREAD

**Issue by igorshubovych** [Automattic/monk#184]
4.0 is released on NPM
![monk 2017-03-23 14-08-18](https://cloud.githubusercontent.com/assets/93907/24247060/c51099c0-0fd2-11e7-9f38-9c66b74e1d91.png)

But there is no release information on Github, so i do not know what is the changelog.
https://github.com/Automattic/monk/releases

**Comment by mathieudutour** [comment]
oops sorry about that

**Comment by mathieudutour** [comment]
(btw, the changelog is also here: https://github.com/Automattic/monk/blob/master/History.md)

**Comment by igorshubovych** [comment]
Thanks!
