### ISSUE TITLE
How to detect when MongoDB connection is down ?

### ISSUE THREAD

**Issue by radiKal07** [Automattic/monk#189]
For example when first creating the connection with MongoDB is successful but after some time the MongoDB server dies and the connection to it drops.

How to get notified in monk about this ?

**Comment by alexborisov** [comment]
Any updates to this? It's pretty annoying to not be able to detect if a connection goes down. This is critical for health checking our services.

**Comment by mathieudutour** [comment]
Starting from v5.0.2, you can listen to the underlying mongo event on your monk instance:
```js
import monk from 'monk'

const db = monk()

db.on('timeout', () => {})
```

You can see the events available here: http://mongodb.github.io/node-mongodb-native/2.1/api/Db.html#event:authenticated

**Comment by radiKal07** [comment]
@mathieudutour thank you really much for the response man. I really appreciate it :smiley:

**Comment by mathieudutour** [comment]
btw, previous to that version (if you can't update yet), you can use `db._db.on('timeout', ...)`

**Comment by alexborisov** [comment]
@mathieudutour Thanks for your answer, but I cannot seem to get this to work. I'm using Monk 5.0.2 and I tried to implement some callbacks that log when the connection is down. I then kill the mongod server and wait. Nothing logs. When I try to make a request (about 30 seconds later) I just get an error _Topology was destroyed_

**Comment by mathieudutour** [comment]
what event did you try to listen to?

**Comment by alexborisov** [comment]
```js
db.on('timeout' => {
  console.log('Mongo connection lost')
})

db.on('close' => {
  console.log('Mongo connection closed')
})

db.on('reconnect' => {
  console.log('Mongo reconnected')
})

db._db.on('timeout' => {
  console.log('Mongo connection lost')
})

db._db.on('close' => {
  console.log('Mongo connection closed')
})

db._db.on('reconnect' => {
  console.log('Mongo reconnected')
})
```

**Comment by mathieudutour** [comment]
maybe `error`? http://mongodb.github.io/node-mongodb-native/2.1/api/Db.html#event:error

**Comment by alexborisov** [comment]
I tried error and also no log. Both on `db` and on `db._db`

**Comment by alexborisov** [comment]
Could we re-open this issue? Unless I am doing something wrong it looks like this doesnt work as intended...

**Comment by mathieudutour** [comment]
well I'm just exposing the raw mongo events. How do you do it with mongo usually?

**Comment by alexborisov** [comment]
Hehe good question. I normally don't use the raw driver. I've used Mongoose which seems to do this and lately I've been using Monk (because I prefer it much more to the heavy weight Mongoose) and this is the first time I need to use this (for health checking on our microservices).

**Comment by alexborisov** [comment]
I mean since I have the raw db object I guess I could hack in something to check liveness by doing a `count()` or something on an empty collection and checking for error...

**Comment by mathieudutour** [comment]
I'm happy to accept a PR if you find a nice way (maybe by digging in mongoose?), but I won't have much time to work on that this week

**Comment by alexborisov** [comment]
Ok sure. I noticed there is some mention of a `keepAlive` option in the native mongo connection options. Perhaps that has something to do with it... I'll try to dig around mongoose source and the native driver to see if I can figure something out. Cheers!

**Comment by alexborisov** [comment]
Hey so I did some testing. I dont know why, but it works now. It's possible there was something else somewhere in my code that was breaking it. I ran this in a separate file and the `close` event gets emitted as expected when the db is killed. Thanks and sorry for the confusion 👍

**Comment by tiagosiebler** [comment]
> db.on('timeout', () => {})

@mathieudutour is the appropriate action in that callback, db.open(connnectionStr)? Similar to how db is first populated?

**Comment by Cognegic** [comment]
Investigate your MongoDB Connection Error with Cognegic's MongoDB Online Support
At whatever point you are attempting to interface with the database then it is possible you have to stand up to MongoDB affiliation issue in light of the way that might be possible your MongoDB database server in erroneously coordinated, at displaying pulled back, frustrated by a firewall and so forth. Regardless, don't solidify; we have the best response for you i.e. [MongoDB Customer Support](https://cognegicsystems.com/rim-support-services/database-management/mongodb-support/) the USA. Here are specific experts can isolate this issue and raise you discipline free. Thus, contact to Cognegic's Support for MongoDB Database Software for the inducing procedure.

**For More Info: [https://cognegicsystems.com/](https://cognegicsystems.com/)
Contact Number: 1-800-450-8670
Email Address- info@cognegicsystems.com
Company’s Address- 507 Copper Square Drive Bethel Connecticut (USA) 06801**
