### ISSUE TITLE
Ensure mongodb uri for replica sets work

### ISSUE THREAD

**Issue by rauchg** [Automattic/monk#19]
We currently support `127.0.0.1/db,127.0.0.2` but I need to make sure `mongodb://127.0.0.1,127.0.0.2/db` works

**Comment by hiddentao** [comment]
I'm in the process of adding connection error checking (#24). When I do so I notice that the replicaset connection tests fail with error `Error: Could not locate any valid servers in initial seed list`. Both `array` and `string` versions fail.

Looking at Mongoskin's README it looks like you actually have to use the native lib's objects when defining a replica set:

```js
var Server = mongo.Server;
var Db = mongo.Db;

var replSet = new ReplSetServers([
        new Server('localhost', 30000),
        new Server('localhost', 30001),
        new Server('localhost', 30002),
]);

var db = new Db('integration_test_', replSet, {w:0, native_parser: (process.env['TEST_NATIVE'] != null)});
```

Do we need to update monk with this then?

**Comment by hiddentao** [comment]
Actually that is't the problem - it works with a real replica set. The test fails because the servers specified in the test code aren't setup for replication.

**Comment by hiddentao** [comment]
Another point I've realised is that a lot of the tests don't explicitly close db connections once done. And this also makes me wonder why connecting to a db isn't made to return a promise. Wouldn't it be nice to have that work the same as the rest of monk?

**Comment by rauchg** [comment]
Agreed
