### ISSUE TITLE
typescript is missing some crucial definitions.

### ISSUE THREAD

**Issue by JoelParke** [Automattic/monk#190]
The latest release: @types/monk  v1.0.5 
is missing some definitions that create lots of problems.

In my local version I added (a few lines near the top of the file) to index.d.ts:

     declare module "monk" {
       function m(database: string): m.Monk;
       module m {
         export interface promise {
           type:string
           on(eventName:string, fn:Function):void;
           error(fn:Function):promise;
           success(fn:Function):promise;
           then(fn:Function):promise;   -- added
           each(fn:Function):promise;  --added
           catch(fn:Function):promise; --added
        }

Without those, one can't do much of the normal calls such as:
 
     db.get('backups').remove({_id: this.getId()})
         .then((res: any) => {
                       ....
                   })
         .catch((err: any) => {
                      ....
                    });  

I am sure that there are a few others, but if you added these, this would be a great help for those using typescript and monk.

**Comment by mathieudutour** [comment]
the types are not defined in this repo. You should probably open an issue there

**Comment by JoelParke** [comment]
I will do, when I figure out where the typescript for monk is supported.
It does strike me as a bit strange that the types aren't included in the
core package since that seems to be how things are progressing.  Thanks for
Monk, its great!!!
