### ISSUE TITLE
Depreciation Warning on Index Creation

### ISSUE THREAD

**Issue by 2yq4hozule8fs** [Automattic/monk#200]
Is there a reason #169 wasn't merged? I'm getting this message: 
```
DEPRECATED (collection.ensureIndex): use collection.createIndex instead (see https://Automattic.github.io/monk/docs/collection/createIndex.html)
```
and I'm only using:
```
// Ensure mongodb index on myCollection.indexedField
myCollection.index('myCollection.indexedField');
```
which if I inspect the repo is probably coming from this line: https://github.com/Automattic/monk/blob/c7e680e44c841b5d29f03876c446f67fa60ddb75/lib/collection.js#L16
```
 this.index = this.ensureIndex = this.ensureIndex.bind(this)
```

**Comment by mathieudutour** [comment]
yes, `ensureIndex` is deprecated (`index` is an alias to ensureIndex) and you should use `createIndex` instead.

I'm not sure what is the issue.

**Comment by 2yq4hozule8fs** [comment]
Thanks for that, I can confirm that replacing:
```
myCollection.index('myCollection.indexedField');
```
with:
```
myCollection.createIndex('myCollection.indexedField', function (err, res) {
  // MWE, if the index already exists then it raises an err
  console.log(err, res);
});
```
does indeed make this warning go away.

Sorry, I didn't understand the depreciation message so it's my fault. I'm not very familiar with this module and didn't realise that `.index` was an alias to `.ensureIndex`.

**Comment by andrewsosa** [comment]
@mathieudutour A lot of the documentation shows using just the `.index(...)` call. For example, the first code snippet in the README.md does this. Would it make sense to either:

  1. Update the docs to show `.createIndex`?
  2. Update `.index` to alias to `.createIndex` instead? 

I actually like the second option as it keeps the syntax concise, but would that be a breaking change?
