### ISSUE TITLE
The field 'fields' is not valid for an index specification.

### ISSUE THREAD

**Issue by ChrisLahaye** [Automattic/monk#203]
Hello,

I am using monk 5.0.2 / 2017-05-22 with MongoDB 3.4.3 and get the following error:

```The field 'fields' is not valid for an index specification. Specification: { ns: "events", key: { location: "2dsphere" }, name: "location_2dsphere", fields: {}, sort: {}, safe: true, castIds: true, wrapNon$UpdateField: true, unique: false }```

when creating an index with```db.get('events').createIndex({location: '2dsphere'})```.

Fields should be removed from the specification.

Thank you,

Best regards,

Chris

**Comment by mathieudutour** [comment]
the test here: https://github.com/Automattic/monk/commit/10ebb57526f63ca412ac75a0f7d708c5bed022d3 pass. Could you create a test case which reproduce your bug? I can't.

**Comment by ChrisLahaye** [comment]
Hello Mathieu,

Thank you for your reply. The test case you created fails on my setup, as mentioned I am using MongoDB 3.4.3. I uploaded my terminal output here: https://asciinema.org/a/35rtvhygsuk9mkxqf88llcfu8

Thank you

**Comment by mathieudutour** [comment]
could you try the branch `fix-options`?

**Comment by ChrisLahaye** [comment]
Unfortunately still the same error.

https://asciinema.org/a/16wrwmahyo8tofzj45ca0m59d

**Comment by mathieudutour** [comment]
Are you sure? Maybe you need to do an `npm i` to update the middlewares. I get `executing command [{"ns":"monk.$cmd","cmd":{"createIndexes":"index-1496523548610","indexes":[{"name":"location_2dsphere","key":{"location":"2dsphere"}}]},"options":{}}]` when running it now

**Comment by ChrisLahaye** [comment]
Hello Mathieu, 

Sorry I didn't know, I assumed changing branches was sufficient.
After updating the packages the test passed, so your solution works.

Many thanks,

Chris
