### ISSUE TITLE
@types/monk

### ISSUE THREAD

**Issue by mustafaekim** [Automattic/monk#204]
Hi, I use monk 5.0.2 and it seems like "@ types/monk" is not compatible with. Am I right? So how can I use monk with TypeScript ?

**Comment by mathieudutour** [comment]
I'm responsible for the @types/monk so I couldn't say.

I tried to create the types here: #205 but I'm not super familiar with typescript. Could you check if there is any mistakes?

**Comment by mustafaekim** [comment]
Hi, if what I need to try is

npm install --save https://github.com/Automattic/monk.git#typescript

then, after I could not import monk into the project by:

import * as monk from "monk";

**Comment by mathieudutour** [comment]
what is the error?

**Comment by mustafaekim** [comment]
Could not find a declaration file for module 'monk'. 'd:/dev/nodespace/peoplive/node_modules/monk/lib/monk.js' implicitly has an 'any' type.

**Comment by mathieudutour** [comment]
oh I'm really not familiar with typescript :/ Can you look at `index.d.ts` and fix it if you have a bit of time? I think I put the entire API but the syntax is probably wrong

**Comment by mustafaekim** [comment]
What I dont understand is @types/monk is completely different from your index.d.ts

I am sure everyone will install @types/monk first because that is the convention

I think that you should just publish your index.d.ts under @types/monk

That is how typescripters start with using a module: npm install monk @types/monk

**Comment by mustafaekim** [comment]
By the way, when I 
npm install --save https://github.com/Automattic/monk.git#typescript 

I dont get your commit. How can I get that exactly?

**Comment by mathieudutour** [comment]
hum it should work. maybe `rm -rf node_modules/monk` and reinstall it?

**Comment by mustafaekim** [comment]
Neither 

> npm install --save https://github.com/Automattic/monk.git#typescript

Nor

> npm install --save https://github.com/Automattic/monk.git#e1c7069dcda5053d7cc89c5cda0188972a7a15e7

installs a index.d.ts file under monk module

**Comment by mathieudutour** [comment]
oh my bad, should work now
