### ISSUE TITLE
Projection on array with $filter

### ISSUE THREAD

**Issue by thierryskoda** [Automattic/monk#206]
Hi,

I just found the $filter in Mongo documentation and tried it in my app and couldn't make it work. Am I missing something or is there a different way to do this with Monk ? 

````
User.findOne({ user: 'ME' }, {
   fields: {
        answers: {
            $filters: {
               input: "$answers",
               as: "answer",
               cond: { 
                   "$$.answer.friend: new ObjectId(AN_USER_ID)
               }
            }
        }
    }
})
````

Answers is an array which as a field user that is a ref to User model. But I don't want all the items in the answers array. 

Thank you for any help!
Thierry

**Comment by mathieudutour** [comment]
never used it but can't find the `$filter` operator in the doc: https://docs.mongodb.com/manual/reference/operator/projection/

**Comment by thierryskoda** [comment]
@mathieudutour Yeah I've looked at it but couldn't make it work. 

Do you know how could I use something like this with Monk. I took this example from this page: https://docs.mongodb.com/manual/reference/operator/aggregation/filter/#exp._S_filter

`````
db.sales.aggregate([
   {
      $project: {
         items: {
            $filter: {
               input: "$items",
               as: "item",
               cond: { $gte: [ "$$item.price", 100 ] }
            }
         }
      }
   }
])
`````

I tried it in my code but I always have `Unrecognized expression '$filters'`

Thank you @mathieudutour  !

**Comment by mathieudutour** [comment]
well yeah it's an aggregation operator so it only works in aggregate

**Comment by thierryskoda** [comment]
Yeah I know but even the example in Mongo doesn't work.

**Comment by mathieudutour** [comment]
maybe you don't have a version recent enough?

I really don't know that's not in the scope of monk, sorry

**Comment by thierryskoda** [comment]
Okay thank you
