### ISSUE TITLE
Connection request treated as a query

### ISSUE THREAD

**Issue by paper1111** [Automattic/monk#211]
I connected to the database as the following:
```
const db = require('monk')('user:examplepassword?@localhost:27017/test');
```
It returns error:
```
Error: query parameter @localhost:27017/test is an incomplete value pair
```
But if the password doesn't have a question mark, it connects. The problem is, my password HAS a question mark, so I can't authenticate to the database.

**Comment by mathieudutour** [comment]
Oh that's a weird one. Did you try `encodeURIComponent` it? (not sure if that will work tho)

**Comment by paper1111** [comment]
Yes it worked.
```
const url = 'user:' + encodeURIComponent('examplepassword') + '@localhost:27017/test';
const db = require('db')(url);
```
Thanks!
