### ISSUE TITLE
Document how to delete a database

### ISSUE THREAD

**Issue by xgvargas** [Automattic/monk#213]
First of all: thanks for `monk`, it's great! :+1: 

I need to delete an existing database previously created with monk, but could not found how to proceed in current documentation.

**Comment by cktang88** [comment]
I think "db.dropDatabase()" should still work.

**Comment by xgvargas** [comment]
@cktang88, no, I'm currently using version 6.0.1

```js
db = monk('host:port/dbname');
db.dropDatabase();

// throws: TypeError: db.dropDatabase is not a function
```

**Comment by cktang88** [comment]
Oh my mistake. According to https://github.com/Automattic/monk/tree/master/docs/manager, the monk constructor only comes with three methods - create, close, and get. So currently my guess is that it doesn't support database deletion. For that, the route I'm currently taking is to connect to the Mongo-Node.js driver directly, and do dropDatabase() from there.

**Comment by mathieudutour** [comment]
you can access the underlying mongo database and drop it like this:

```js
monk('host:port/dbname').then((underlyingDB) => {
   underlyingDB.dropDatabase()
})

or 

db = monk('host:port/dbname'); // need to wait for the promise to resolve before trying to access _db tho
db._db.dropDatabase();
```

**Comment by mathieudutour** [comment]
oh I though I was passing the underlyingDB in the promise, my bad. You should be able to access it with
```js
monk('host:port/dbname').then((db) => {
   db._db.dropDatabase()
})
```
tho.

As for why `dropDatabase` doesn't, I couldn't say, never used it^^

**Comment by xgvargas** [comment]
@mathieudutour, you are right, using the `_db` inside promisse works too. And I was right too, about being my fault the failure of dropDatabase :smile:! I wasn't giving it time to finish before finishing my process. Now I'm finishing inside the `dropDatabase`'s callback and it is working!

```js
monk('host:port/dbname').then((db) => {
   db._db.dropDatabase(function(err, result) {done()});
})
```

`_db` was a good tip! Thanks! I think it should be well documented (I don't think it's documented at all)

**Comment by mathieudutour** [comment]
indeed it's not because it's a private API ;)
