### ISSUE TITLE
Middleware per request

### ISSUE THREAD

**Issue by bkniffler** [Automattic/monk#215]
Hey, 
I love the concept of using middlewares. But as far as I see, these are only used globally for the whole monk/mongo instance. I'd love to be able to create an instance of monk with middlewares applied per request basis, so data can be filtered by some user fields. Something like that:

```jsx
const db = require('monk')('localhost/mydb')
server.use((req, res, next) => {
   const clone = db.clone();
   // Add a monk middleware that filters data by userid
   clone.addMiddleware(context => next => (args, method) => {
     return next(args, method).then((res) => {
        return res.filter(x => x.userId === req.user.id);
   });
   req.db = clone;
   next();
})
server.use(graphql)
```

Would this be hard to implement? Any thoughts about this?

**Comment by mathieudutour** [comment]
Hum that seems hard yeah.

How about passing the userId as an option of the query? So you could do something like this:
```js
context => next => (args, method) => {
  // check if the userId field is set in the options and store it
  const userId = (args.options || {}).userId

  // if it is, remote so that it doesn't pollute the query
  if (typeof userId !== 'undefined') {
    delete args.options. userId
  }


  return next(args, method).then((res) => {
    if (typeof userId !== 'undefined') {
      return res.filter(x => x.userId === userId);
    }
    return res
  }
}
```

**Comment by bkniffler** [comment]
Hey, thanks for the fast response! But how do I pass the args on a per-request base? I thought I could only add options via the .addMiddleware function.

**Comment by mathieudutour** [comment]
`db.find({}, {userId: req.user.id})`

**Comment by bkniffler** [comment]
Woops, alright, that was obvious. Thanks a ton, works perfectly! Keep up the great work!
