### ISSUE TITLE
How to use  monk find  to access nested items .

### ISSUE THREAD

**Issue by badger27** [Automattic/monk#217]
Below Im trying to select all checked items in all items in my collection.
I can filter on the top level easily but when i try to step into an the tracks array I run into problems.

See code below 

> {
    "_id" : ObjectId("596bd60c8dbf00c0cc562cc8"),
    "artist" : "Ryan Blyth",
    "artistLower" : "ryan blyth",
    "album" : "Trust Me",
    "tracks" : [
        {
            "artist" : "Ryan Blyth",
            "checked" : true
        }
    ]
}

clearChecked: function (callback) {
    contentItems
        .find({'tracks':{checked:true}}).then(function (doc) {
        console.log("check doc ", doc);
    });
}

**Comment by mathieudutour** [comment]
so it would be
```
contentItems
.find({'tracks.checked': true}).then(function (doc) {
console.log("check doc ", doc);
});
```

**Comment by badger27** [comment]
I thought as much but doc comes back empty.

I think monk has an issue with the  "."

**Comment by mathieudutour** [comment]
definitely working, this test pass:
```
test('find > should find with nested query', (t) => {
  return users.insert([{ nested: { a: 1 } }, { nested: { a: 2 } }]).then(() => {
    return users.find({ 'nested.a': 1 })
  }).then((docs) => {
    t.is(docs.length, 1)
    t.is(docs[0].nested.a, 1)
  })
})
```

So it's probably coming from your code

**Comment by badger27** [comment]
Hmm, thanks for taking a look. I'll retry it

**Comment by badger27** [comment]
Hey Mathieu,

I was only able to solve this issue by using a match element
see below

contentItems
    .find({"tracks":{"$elemMatch":{"checked": true}}}).then(function (doc) {
    console.log("check doc ", doc);



})


The . operator isnt letting me step into nested arrays. Not sure why.

Thought you might like to know incase you see it again.

Thanks to your  all your help on this.

**Comment by mathieudutour** [comment]
Cool thanks
