### ISSUE TITLE
Unable to use self assigned strings as _id

### ISSUE THREAD

**Issue by animeshjain** [Automattic/monk#220]
Hi, Mongo allows usage of any arbitrary strings for the `_id` field. However monk throws an error as follows when trying to insert a document with a custom string in the `_id` field.

```
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
```

I feel the code in `helper.js` on line number 13 is a little weird.
```
return typeof str === 'string' ? ObjectId.createFromHexString(str) : str
```

Based on this code, it always tries to create an ObjectId object, and a custom string id always throws an error. All works well with the native mongo driver.

**Comment by mathieudutour** [comment]
There is a castIds option the you can set to false to use arbitrary strings for _id
