### ISSUE TITLE
Memory leak if collections are not cached

### ISSUE THREAD

**Issue by henit** [Automattic/monk#225]
Hi.

I have just spent a few too many hours trying to solve a problem causing my node application to stop working in production after a few hours. Node gave no error output of any kind, but kept running with high cpu use, so it was a bit hard to debug.

Anyways, the reason for Node failing, was a memory leak somewhere in monk. It happened because a code update included going from caching collections to not getting them from monk on every db-query. That was a mistake obviously, but I am still thinking that although asking for the collection from monk for every query might not be the best solution, it should not cause a memory leak that leads to the applications dying.

Examplified code of how it was before when it worked:

    let collections = {};
    getCollection(name) {
        collections[name] = collections[name] || monk(dbUrl).get(name);
        return collections[name];
    }

Examplified code of how it was when it caused memory leak

    getCollection(name) {
        return monk(dbUrl).get(name);
    }

I don't know if this is something you would consider a bug, just posting it for information and in case someone else encounter a similar problem.

**Comment by mathieudutour** [comment]
to be clear, the part that's leaking is `monk(dbUrl)`, not `.get(name)`.

`monk(dbUrl)` create a new connection every time, it's a new object. If you don't recreate the object every time, the collections are already cached: https://github.com/Automattic/monk/blob/master/lib/manager.js#L245-L260

The only fix would be the one in https://github.com/Automattic/monk/issues/70 so I'll close this one. Feel free to input in the other one
