### ISSUE TITLE
Monk callbacks are not callbacks

### ISSUE THREAD

**Issue by nekdolan** [Automattic/monk#226]
Hi there,

This is a very nice library. I took over a project 6 months ago that used monk and I was mostly happy with it, but should the opportunity rise I'm not sure I will stick with it. 
My main (and only) reason for switching is that monk's callbacks exist inside promises which make them act differently from traditional callbacks.

For example consider this code:
`db.get('user').findOne({}, (err, doc) => var_does_not_exist+1 );`
In nodeJS we might get a warning like...
> (node:23876) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: var_does_not_exist is not defined

...which at least gives us some info, but it does not crash the app and it does not give us a stacktrace. 

End the problem does not stop there. If I want to use the callback inside some group async call it will change the async callback as well:
```
async.parallel({
    stat : (cb) => fs.lstat('.', cb),
    user : (cb) =>  db.get('user').findOne({}, cb)
}, function (err, result) {
    var_does_not_exist+1;
});
```
This will produce the same warning as the code above (if the node version is high enough)

I know (or at least that's what I remember) that we can use additional modules to debug promises, but what if that is not an option (because of managment/devops)?
I used to use promises a lot back in the day, but I've found that the simplicity of callbacks make them more manageable. That is only a personal preference, but I don't think that it is a good thing to be "forced" to deal with the nightmare of promise debugging.

As far as I know other libraries separate the callback from the promise functionality. For example promise-async does that.

Anyway, good luck with the project.

**Comment by mathieudutour** [comment]
I think it fixed it in `monk-middleware-handle-callback@0.2.1`, it was simple enough: https://github.com/Automattic/monk/commit/2f21ca1e2255e042afb66ae63b38b05942f95ecd ;)

Can you check if it is indeed working as expected?

**Comment by nekdolan** [comment]
I checked. It does not work as it should. I get almost the same result.

What we want is to throw an error that could potentially crash the app. 
(Example: `fs.lstat('.', (err, stats) => var_does_not_exist+1);` )

What this solution will do is call the same callback that has already failed once with the error that was the result of the first failure. Or at least that's what it should, but when I tested it actually called the callback three times instead of the two that I expected. 
Calling the same callback a second time is not a good solution. Writing the error on the console might be slightly better but it is still no a proper crash.

Once you put yourself into the position of using Promises instead of functions you won't be able to throw errors as you would normally do. From what I saw in the code base it seemed that refactoring was the only solution. Alternatively hacking some basic event handlers could also do the trick but that is probably not a very good solution.

**Comment by mathieudutour** [comment]
yeah you are right, I don't think there is an easy solution (or even if there is one) if we want to keep the middlewares

**Comment by nekdolan** [comment]
Somebody suggested this trick to break out of any promise: 
```
db.get('user').findOne({}, (err, doc) => {var_does_not_exist+1} )
    .catch((e) => setImmediate(()=> {throw e}));
```
This will crash and give a stacktrace. (setTimeout also works) .
It is a bit hacky, but it should be fine since the whole thing is supposed to be async anyway.

To also call the fail branch of any promise we can do:
`.catch((e) => {setImmediate(()=> {throw e}); throw e; })`

Unfortunately the callback gets called twice if it throws an error (even older versions of monk) regardless of the catch statement at the end.

**Comment by mathieudutour** [comment]
published a new version of `monk-middleware-handle-callback` which uses this nice trick to break out of the promise chain when there is a callback

**Comment by nekdolan** [comment]
Looks good, but including the middleware will invoke the callback twice regardless of any error:
```
db.addMiddleware(require('monk-middleware-handle-callback'));
db.get('user').findOne({}, (err, doc) => {console.log('invoked');} );
```
Will output:
> invoked
> invoked

Instead of:
> invoked

Which is the result if the middlware is not attached.

**Comment by mathieudutour** [comment]
oh but it's included by default

**Comment by nekdolan** [comment]
Ah, so that's why :)
