### ISSUE TITLE
Typescript: Property 'findOneAndUpdate' does not exist on type 'Collection'

### ISSUE THREAD

**Issue by technicatisatio334455** [Automattic/monk#228]
Hi! Seems to be an issue with the typing for `findOneAndUpdate`.

Example: `monk('localhost').get('collection').findOneAndUpdate({}, {})`
Gives: "Property 'findOneAndUpdate' does not exist on type 'Collection'" by the TypeScript compiler.

While for example: `monk('localhost').get('collection').find({}) ` Works as expected so don't think it's my project. Also tried with `.findOne` which also works well.

**Comment by mathieudutour** [comment]
seems like it's there: https://github.com/Automattic/monk/blob/master/index.d.ts#L49

can you make sure you are using the latest version?

**Comment by technicatisatio334455** [comment]
My mistake, saw that and couldn't figure out why it didn't work. I had @types/monk installed which got priority.
