### ISSUE TITLE
Promise not rejecting correctly on manager chaining

### ISSUE THREAD

**Issue by maoueh** [Automattic/monk#239]
The following code prints 'Error!' correctly when MongoDB instance is down:

```
require('monk')('mongodb://localhost:27017/any').then(() => { 
  console.log('Connected'); 
}).catch(() => {
  console.log('Error!');
});
```

While this code does not print nothing and simply stop (when used as the "main" code of a script):

```
require('monk')('mongodb://localhost:27017/any').get('collection').find({}).then(() => { 
  console.log('Connected'); 
}).catch(() => {
  console.log('Error!');
});
```

Is it incorrect to chain them? Might also be a misusage from my part. Note that if the database is up and running, the second snippet works and prints `Connected!` correctly.

**Comment by mathieudutour** [comment]
well you don't really chain them: in the first example, you call `then` and `catch` on the connection promise while in the second example, you call `then` and `catch` on a `find` promise.

you can rewrite it like this:

```js
const db = require('monk')('mongodb://localhost:27017/any').then(() => { 
  console.log('Connected'); 
}).catch(() => {
  console.log('Error!');
});

db.get('collection').find({}).then(console.log) // will only be loged after `Connected!` has be printed. monk automatically queues queries while waiting for a connection to open
```

**Comment by maoueh** [comment]
Shouldn't the `find` promise reject when connection cannot be opened?

I was thinking of doing the way I did so auto-reconnect works out of the box while error still being forwarded to caller via the `find` rejection.

What would be the proper way of handling re-connection correctly if the MongoDB instance ever go down?

Currently, I create the manager instance once (without explicit connection) and each operation calls `db.get(...).<something>` to perform the operation, that was working great but if the connection cannot be opened, the operation promise is not rejected leading to problems.

Maybe you can give me some hints/ideas about how to properly do it.

Thanks for the quick response by the way.

**Comment by mathieudutour** [comment]
> Shouldn't the find promise reject when connection cannot be opened?

not it's just going to wait until a connection opens. The query didn't fail, it just wasn't executed.

you can reconnect in the `catch` of the connection promise.

**Comment by maoueh** [comment]
Ok make senses, I understand better now. Going to create something around it, thank you.

**Comment by roastlechon** [comment]
Im having issues with this relating to async/await.

I would like to handle any connection errors as a 503 and not continue the chain, however if i do the following:

```
export const getDb = () => new Promise((resolve, reject) => {
  monk(getUrl(), {
    autoReconnect: false,
    bufferMaxEntries: 0,
  }, (err, db) => {
    if (err) return reject(err);
    return resolve(db);
  });
});

const db = await getDb();
const stuff = await db.get('somecollection').find({});
```

...it hangs on the `const db = await getDb();` and never gets to the find.

When I close the database, it works correctly where the application rejects and I am able to catch MongoError and return 503 status.

I would like to not hang the application and respond immediately if there is an issue with mongodb.

**Comment by mathieudutour** [comment]
wait you probably shouldn't open a connection for each request, it's super slow. Any reason to do that?

**Comment by roastlechon** [comment]
Ideally I'd like to reuse connection but in this example it does not recover from mongodb turning off. It simply hangs on getDb. If this were to work correctly I would reuse connection in the getDb function via Singleton
