### ISSUE TITLE
async monk?

### ISSUE THREAD

**Issue by kolykhalov** [Automattic/monk#240]
Hello there!

why this returns nothing?

var connected = await monk(localhost/db)
console.log(connected)

not undefined, just empty console.

**Comment by flypart** [comment]
I have got the same problem.
Have you found any solution ?

**Comment by kolykhalov** [comment]
@flypart there is no solution apart using Callbacks, Promises or switching to mongoose.

try something like that:
```
function conn(){
    return new Promise ((resolve)=>{
        monk(localhost/db, (data)=>{
if(data.connected){resolve(true)}}
    })
}
async function conWait(){
    var x = await conn()
    console.log(x)
}

con()
```

Please check that monk returns "data" parameter and check its values. I haven't used monk for long time.

**Comment by flypart** [comment]
Thank you! I will have a try.
Maybe I will turn back to original MongoDB api (types/mongodb) or Mongoose...
