### ISSUE TITLE
Ability to globally remove castIds behavior?

### ISSUE THREAD

**Issue by Siyfion** [Automattic/monk#243]
Essentially I've done the following:

In the main db setup file:
```
import monk from 'monk';
module.exports = monk(process.env.DB_URI, { castIds: false });
```

In every module that utilizes a collection:
```
const products = db.get('products', { castIds: false });
const recipes = db.get('recipes', { castIds: false });
const printLists = db.get('printLists', { castIds: false });
```

I'm not sure how much more explicit I need to be that I do **NOT** want any casting to be applied, but it seems that it's not enough, and every operation _also_ needs the flag. Is there really no way to easily just remove the castIds middleware entirely?

**Comment by mathieudutour** [comment]
it should be `module.exports = monk(process.env.DB_URI, { collectionOptions: { castIds: false } });`

**Comment by SacDin** [comment]
12321
