### ISSUE TITLE
Monk does not accept guid as ObjectId

### ISSUE THREAD

**Issue by kolykhalov** [Automattic/monk#248]
Hi there!

Monk does not accept guids as _id
`var id = 'A71875CA-1BB5-40F0-BA2B-A1BF5C0ABF96`
`var user = await db.get('users').find({'_id': id})`

and posts: 

> Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

but MongoDb accepts it natively:

`db.users.find({'_id':'A71875CA-1BB5-40F0-BA2B-A1BF5C0ABF96'})`

> { "_id" : "A71875CA-1BB5-40F0-BA2B-A1BF5C0ABF96"}

Is it a bug in Monk? Is there some bypass of it? I tried to convert it like `monk.id (id)` but get the same error

**Comment by mathieudutour** [comment]
yes, use the `castIds` option: https://automattic.github.io/monk/docs/id.html
