### ISSUE TITLE
not support skip and limit?

### ISSUE THREAD

**Issue by AlfieriChou** [Automattic/monk#259]
pagination is not suport

**Comment by b3rew** [comment]
I cant find this anywhere but this  seems to work

`Model.find({}, { limit: 5, skip: 5 })`

**Comment by AlfieriChou** [comment]
@b3rew So i choice mongoose or mongodb native to aviod this question, but I hope development this function to support pagination.

**Comment by RobertoMachorro** [comment]
@AlfieriChou Unless we don't understand your question, the response given by @b3rew is correct and pagination is supported. Maybe some in-context code will help?

```
collection.find({}, { limit: 20, skip: 100 }).then(docs => {
	t.equals(docs.length, 20, 'correct length')
})
```

**Comment by RobertoMachorro** [comment]
I got to thinking, maybe you are asking for a *raw cursor*? You can do that in Monk, and still process that back to an array of docs:

```
return collection.find({}, { rawCursor: true })
}).then(cursor => {
	return new Promise(function(resolve, reject) {
		// now you are in mongodb-native world here...
		cursor.skip(100).limit(20).toArray(function(err, docs) {
			if (err) reject(err)
			resolve(docs)
		})
	})
}).then(docs => {
	t.equals(docs.length, 20, 'correct length')
})
```

Please advise if that is what you are looking for.
