### ISSUE TITLE
Insert deprecation warnings

### ISSUE THREAD

**Issue by Boycce** [Automattic/monk#276]
Receiving a deprecation warnings while using `collection.insert` (`v7.0.0`)

> (node:10450) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.

**Comment by tomiolah1998** [comment]
Can confirm this.
`collection.count` also gives DeprecationWarning:

```
(node:4536) DeprecationWarning: collection.count is deprecated, and will be removed in a future version.
Use collection.countDocuments or collection.estimatedDocumentCount instead
```

**Comment by ostrebler** [comment]
Same with `find` :

```(node:9712) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.```

**Comment by imanabu** [comment]
Also happening with me:

    public static insert<T extends IZDoc>(doc: T, collectionName: ZSDocument): Promise<T> {
        const my = this;
        const db = my.getFormDb();
        const c = db.get(collectionName);
        return c.insert<T>(doc);
    }

**Comment by ramwolken9** [comment]
Any updates on this issue ?

**Comment by drojasdev** [comment]
Definitely having this issue too.

`(node:29974) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.`

`    "monk": "^7.0.0",`

**Comment by RobertoMachorro** [comment]
I was having this issue as well. I've noticed a bunch of MongoDB 3.x related updates affecting Monk. For now I've got fixes for the *insert DeprecationWarning*, please feel free to give them a try - i'll do a  Pull Request back to Monk as well.

Issue the following commands on your project:
```
npm uinstall monk
npm install --save RobertoMachorro/monk#insert-deprecation
```
GitHub Source: [https://github.com/RobertoMachorro/monk/tree/insert-deprecation](https://github.com/RobertoMachorro/monk/tree/insert-deprecation)
