### ISSUE TITLE
package-lock.json isn't commited

### ISSUE THREAD

**Issue by RobertoMachorro** [Automattic/monk#279]
While not an impediment for build or deployment, the file (according to the documentation) *"is intended to be committed into source repositories"*:

[https://docs.npmjs.com/files/package-lock.json](https://docs.npmjs.com/files/package-lock.json)

And makes a difference when building elsewhere avoiding compatibility issues between module versions.

**Comment by mathieudutour** [comment]
It's intended to be committed in case you are building an application. Not really when you are building a library
