### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by severussnape357** [Automattic/monk#281]
(node:6393) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

and insertOne is deprecated

**Comment by faradaytrs** [comment]
Insert is already merged in master, we need to wait for the release, also count is deprecated, but not fixed. 
pass option { useUnifiedTopology: true } Actually you can temporary pass it yourself during initialization const db = require("monk")("localhost/db", {useUnifiedTopology: true});

**Comment by mathieudutour** [comment]
fixed in 7.1.0
