### ISSUE TITLE
mongo+srv:// URL not supported

### ISSUE THREAD

**Issue by ewrogers** [Automattic/monk#282]
Looking at https://github.com/Automattic/monk/blob/master/lib/manager.js#L87, the regex will cause `mongo+srv://` URL schemes to be clobbered.

The 3.x MongoClient driver allows such URLs, and are often seen when using Mongo Atlas. Is there more to enabling this functionality than just fixing the regex?

**Comment by s-zimm** [comment]
Experiencing a similar problem. Created the PR in case there are no other considerations to be made.
