### ISSUE TITLE
How can I get a "pure" MongoDb instance from Monk?

### ISSUE THREAD

**Issue by thardy** [Automattic/monk#284]
I have a third party library that needs a MongoDb instance.  When I use the mongodb driver directly and hand the library the following db object, it works great...

```
this.client = await mongoDb.MongoClient.connect(config.mongoDbUrl,{ useUnifiedTopology: true, useNewUrlParser:true });
console.log('mongoDb connected');
// this.db is exactly what the library needs
this.db = this.client.db(config.databaseName);

```
I've got Monk tightly integrated all over my application.  I would love to be able to simply get the above db instance from Monk, but I haven't been able to figure out how to do so.

Everything I've tried gives errors like...
TypeError: this._mdb.collection is not a function

**Comment by osban** [comment]
@thardy can't you do something like `this.db = require('monk')(config.mongoDbUrl + '/' + config.databaseName)`?

**Comment by thardy** [comment]
That's what I'm using.  I think the problem is with my third party library.  I just found an issue that looks a whole lot like mine, along with a potential fix.  Once I track it down, and it proves to be the other library, I will close this.

**Comment by mathieudutour** [comment]
Once you have `this.db = require('monk')(config.mongoDbUrl + '/' + config.databaseName)`, you can use `this.db._db` or `this.db._client` to access the underlying mongodb object
