### ISSUE TITLE
addMiddleware modifies internal default array

### ISSUE THREAD

**Issue by lolgesten** [Automattic/monk#288]
In a test suite, I setup monk once per test. When using `addMiddleware()` this triggers a bug where we get "hangover" middleware from every test run.

The constructor sets up default middleware (part of DEFAULT_OPTIONS) https://github.com/Automattic/monk/blob/master/lib/manager.js#L70:

```js
this._collectionOptions = objectAssign({}, DEFAULT_OPTIONS, opts.collectionOptions || {})
```

Since DEAFULT_OPTIONS is not deep copied or similar, if we use `addMiddleware()`, we modify the DEFAULT_OPTIONS array since `._collectionOptions.middlewares` points to the original default array.

```js
Manager.prototype.addMiddleware = function (middleware) {
  if (!this._collectionOptions) {
    this._collectionOptions = {}
  }
  if (!this._collectionOptions.middlewares) {
    this._collectionOptions.middlewares = []
  }
  this._collectionOptions.middlewares.push(middleware)
}
```

**Comment by mathieudutour** [comment]
ah good catch. Want to send a PR?

**Comment by lolgesten** [comment]
Sure!

**Comment by mathieudutour** [comment]
Thanks!
