### ISSUE TITLE
[Typescript] Incompleted type for createIndex

### ISSUE THREAD

**Issue by ostrebler** [Automattic/monk#292]
The current signature of `createIndex` is :

```
createIndex(
      fields?: TFields | { [key: string]: 1 | -1  },
      options?: Object
    ): Promise<string>
```

Isn't `"text"` missing as a valid value for an index ?

**Comment by mathieudutour** [comment]
I think it should already be accepted since `TFields` is `string | Array<string>`?

**Comment by cupcakearmy** [comment]
@ostrebler  should be fixed in the latest version
