### ISSUE TITLE
`Collection.count` is deprecated but `Collection.countDocuments` and `Collection.estimatedDocumentCount` are not functions

### ISSUE THREAD

**Issue by jeancarlozapata** [Automattic/monk#297]
Hi!

I'm having trouble trying to count items in a collection. The current documentation says that you have to use the method `count` in a collection, but when I use it, it throws a deprecation message:

```
(node:14328) DeprecationWarning: myCollection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
```

but when I try to use any of the recommended methods, both throw an exception:

```
TypeError: myCollection.countDocuments is not a function
```
```
TypeError: myCollection.estimatedDocumentCount is not a function
```

I'm using `monk` version `7.1.2`:

```
{
  "dependencies": {
    "monk": "^7.1.2"
  }
}
```

**Comment by osban** [comment]
@jeancarlozapata I think the warning is a MongoDB warning, not a Monk one. Currently Monk doesn't support those new methods that are mentioned in the warning, so I think you can continue to use `count` and ignore the warning.

**Comment by jeancarlozapata** [comment]
@osban you are correct, the deprecation notice is coming from Mongo itself. The problem was yesterday it was returning `undefined` instead of the count. Not sure why it wasn't working. I reinstalled my local `mongodb` instance, used the same code and now it's all working fine.

False alarm 😅  sorry and thank you for your answer!

**Comment by bit-cmdr** [comment]
Out of curiosity, why doesn’t monk support the new methods? I searched issues and I only found this and the other closed issue #276.

**Comment by mathieudutour** [comment]
Because nobody sent a PR to support them!

Happy to review and merge one if you want to work on it 👍

**Comment by bit-cmdr** [comment]
relates to #299
