### ISSUE TITLE
Collection docs reference deprecated fields option

### ISSUE THREAD

**Issue by w33ble** [Automattic/monk#303]
I noticed this when using `findOne`. I had naively followed the monk docs and passed a `fields` option to the method. However, that option has been deprecated for at least a couple years based on the mongodb commits. You can also see that it's deprecated [in the mongodb docs](http://mongodb.github.io/node-mongodb-native/3.2/api/Collection.html#findOne) which are linked to from the monk docs.

The monk docs should probably be updated to use the `projection` option instead, which is a direct replacement for `fields`.

**Comment by matburnham** [comment]
While #304 fixes this in terms of [`findOne`](https://automattic.github.io/monk/docs/collection/findOne.html)'s documentation there are still references to `fields` in other places such as the [`find`](https://automattic.github.io/monk/docs/collection/find.html) documentation. These should also be fixed.

Also see #308 for more concerns re: this documentation not quite reflecting reality and sending me  down a rabbit hole.
