### ISSUE TITLE
Connecting to MongoDb Atlas collection

### ISSUE THREAD

**Issue by KushagraPan** [Automattic/monk#307]
A step by step process to connect to a collection in  MongoDb Atlas  using mongdb+srv url? Couldn't find anything in the docs.

**Comment by konstanzzz** [comment]
> A step by step process to connect to a collection in MongoDb Atlas using mongdb+srv url? Couldn't find anything in the docs.

```
const db = monk('mongodb+srv://username:password@example.mongodb.net/test')
db.get('collection')
```

**Comment by cupcakearmy** [comment]
Can confirm this works :)
