### ISSUE TITLE
Missmatch between undefined/null

### ISSUE THREAD

**Issue by mathiasmagnusson** [Automattic/monk#312]
In index.d.ts (around line 153) it is stated that findOne, findOneAndDelete, and findOneAndUpdate return a Promise of the collection type, or undefined.

But in fact all of these return null, not undefined when no document is found.

This is quite annoying when using TypeScript, since it will error with `Object is possibly undefined` if you do not check for this, but checking with `!== undefined` only calms typescript down. It does nothing at runtime. However, checking with `!= undefined`, or checking if the object is truthy does work at both compiletime and runtime.

**Comment by cupcakearmy** [comment]
I noticed as well.
Also:
- `insert` requires an Object and not the Generic type T. 
- find, findOne should return the generic T + the _id.

I would be happy to update all the types if the maintainers are ok with it :)

**Comment by cupcakearmy** [comment]
I'm working on it. 
@mathieudutour would it be ok if I add the `@types/mongo` dependency? It works really well and then both JS and TS people get the official supported flags, options, queries and so :)

**Comment by mathieudutour** [comment]
Absolutely yes

**Comment by cupcakearmy** [comment]
@mathieudutour Should I remove the types for group as it is deprecated? or better leave them in with a deprecation notice?

**Comment by cupcakearmy** [comment]
@mathieudutour pr is out :) if there are any problems let me know!
