### ISSUE TITLE
[help] how get the array a array with users.find

### ISSUE THREAD

**Issue by mirsella** [Automattic/monk#329]
hello i can't manage to get an array and couldn't find an example for arrays anywhere.

`repofiles.find({})` :
```
[
  { _id: 600443143030ca566fbc67e0, a: [ 'aezf', 'qdgb', 'sdfb' ] },
  { _id: 600443143030ca566fbc67e1, b: [ 'azegezf', 'qdzeggb', 'sdzegfb' ] }
]
```
and i want to get [ 'aezf', 'qdgb', 'sdfb' ] which is "a".
I tried a lot of things, everything I could think of, but couldn't get it, always return a empty array.
just find for "a" as it's unique, it will not have duplicates, but i couldn't find how to do it.
I'm sorry for posting this here, but I think the example for find is lightweight, maybe one more example with a similar configuration would be useful.
thanks

**Comment by mathieudutour** [comment]
I think `repofiles.find({ pictures: { $exists: true } })` should work but that's a mongodb question that isn't related to monk. Do ask on stackoverflow for those type of questions
