### ISSUE TITLE
Insert doesn't cast the ids if an array of documents is passed

### ISSUE THREAD

**Issue by alFReD-NSH** [Automattic/monk#41]
According to this line, https://github.com/LearnBoost/monk/blob/master/lib/collection.js#L314

The cast will be done on the array, not the documents inside if we pass an array to insert.

**Comment by mathieudutour** [comment]
I'll close this as it is really old. Feel free to open a new issue if it's still an issue.

**Comment by alFReD-NSH** [comment]
Just checked, this was fixed with a401f687abf03e7eb815bd52bf908dd50500c643.
