### ISSUE TITLE
dereference?

### ISSUE THREAD

**Issue by catindev** [Automattic/monk#46]
var db = require('monk')(_params_)
db.dereference(_ref_,callback)  not working

**Comment by daimajia** [comment]
+1

**Comment by travisjeffery** [comment]
We don't say that we support that api in the docs, I don't find db refs necessary really either imo.

**Comment by daimajia** [comment]
@travisjeffery Is there any convenient way to do one to many or many to many relations?

**Comment by travisjeffery** [comment]
@daimajia I'd do the same as this article: http://blog.markstarkman.com/blog/2011/09/15/mongodb-many-to-many-relationship-data-modeling/. Like it says in the article, you only need to use DBRef's in the array if your collection names change, in which case you could a write a migration anyway.

**Comment by daimajia** [comment]
@travisjeffery I viewed this post before. How about one to many, for example:

```javascript
db.person.insert({
  "_id": ObjectId("4e54ed9f48dc5922c0094a43"),
  "firstName": "Joe",
  "lastName": "Mongo",
  "groups": [
    ObjectId("4e54ed9f48dc5922c0094a42"),
    ObjectId("4e54ed9f48dc5922c0094a41")
  ]
});
```

How can i quikly get the instance of the `ObjectId("4e54ed9f48dc5922c0094a42")` and `ObjectId("4e54ed9f48dc5922c0094a41")` after I do `find({_id: '4e54ed9f48dc5922c0094a43'})` method using monk?
another query?

**Comment by travisjeffery** [comment]
Yeah another query like so:

``` js
var person; // person you have above
var groups = db.groups.find({"_id": {"$in": person.groups }});
```

**Comment by daimajia** [comment]
@travisjeffery I'm new to mongodb. Thanks a lot for your help. I'll have a try. :-D

**Comment by daimajia** [comment]
@travisjeffery  One more question. How can I bind the `db.groups.find` result with the `person.groups` column? Do it manually using underscore?

**Comment by mathieudutour** [comment]
I implemented a middleware architecture and a dereferencing middleware here: https://github.com/monk-middlewares/monk-middleware-dereference
