### ISSUE TITLE
assumes all _id's are ObjectId

### ISSUE THREAD

**Issue by tj** [Automattic/monk#72]
we use custom ids so this just explodes with "Argument passed in must be a single String of 12 bytes or a string of 24 hex characters" and renders it useless, is there any way to bypass the exploding?

**Comment by wettowelreactor** [comment]
At a minimum when auto casting _id Monk should just fail the promise returned rather than throwing an error.

**Comment by AlexDenisov** [comment]
Just in case you found this issue but it was not clear how on the Earth one fixes the problem.
This will do the trick (notice the `castIds` option):
```js
var collection = db.get("FooBar");

var ids = [ "foo", "bar", "buzz", "" ];

collection.find({ '_id' : { "$in" : ids } }, { castIds: false }, function(error, object) {
  // do your job here
});
```

**Comment by mathieudutour** [comment]
you can also set the options for the entire collection:
```
var collection = db.get("FooBar", { castIds: false });
```
