### ISSUE TITLE
Controlling Connection timeouts? 

### ISSUE THREAD

**Issue by davidsinclair** [Automattic/monk#77]
Hi,

I am new to Monk but have found it very useful in writing a rest web service backed by mongodb.   However, in writing some unit tests for my REST web service I realised that I do not have a way to control connections timeouts.  

How would I go about specifying that requests should timeout after say 2 seconds? 

Thanks,

David

**Comment by hiddentao** [comment]
Don't see any way of doing this in the codebase.

**Comment by mathieudutour** [comment]
you can pass an `options` object as the second argument of the connection (after the url string). https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#mongoclient-connect-options
