### ISSUE TITLE
Invalid Database Name Error for Valid Database Names

### ISSUE THREAD

**Issue by alvintownsend** [Automattic/monk#78]
Apologies in advance if this isn't a monk issue, however in ```mongodb/lib/mongodb/db.js``` line 233, I am being told that my database name is invalid:

```
Error: database names cannot contain the character '.'
```

My database name looks pretty valid to me:

```
my-database-name,10.*.*.*:27017
```
(IP address masked to protect the innocent, but it's a real IP address)

Am I being obtuse for expecting an IP address or fully qualified domain name to work in this instance?

**Comment by mathieudutour** [comment]
monk uses the connection string of mongo: https://docs.mongodb.com/manual/reference/connection-string/
I'm not sure where you have seen this format `10.*.*.*:27017/my-db,10.*.*.*:27017/my-db,10.*.*.*:27017/my-db` anywhere but it doesn't work yes.
