### ISSUE TITLE
Use mongodb functions.

### ISSUE THREAD

**Issue by ronaldohoch** [Automattic/monk#80]
There's a way to load and use the functions from mongodb?
For example, in robomongo i do it:
```javascript
db.loadServerScripts();
db.users.insert({
    _id:getNextSequence("users"),
    name:"Teste",
    password:"000"
})
```

Thank you.

**Comment by lolobosse** [comment]
Hey,

Got the same issue, have business logic on the db (I know, it is bad);

You can solve it by using the native driver:

Like that for instance:

```javascript
var nativeDB;
var MongoClient = require('mongodb').MongoClient;
MongoClient.connect("mongodb://localhost:27017/" + database, function(err, db) {
    if(!err) {
        console.log("We are connected");
        nativeDB = db;
    }
});
nativeDB.eval("jobsDayPerDay()", function (err, result) {
        res.send(result);
})
```

But then you do not use the lib anymore, you directly access the layer under it, it is not a good practise but it kind of work 😄

**Comment by mathieudutour** [comment]
I'll close this issue as, like you said, having logic on the db is bad ;)

Having said that, you can still use monk to access the raw db:
```
const db = monk(...)
db.executeWhenOpened().then((rawDb) => {
    rawDb.eval("jobsDayPerDay()", function (err, result) {
      res.send(result);
    })
})
```
`executeWhenOpened` is a private API so use it at your own risk
