### ISSUE TITLE
MongoDB style connection URL support

### ISSUE THREAD

**Issue by tracker1** [Automattic/monk#84]
It's not quite obvious if this is already supported, but if not... It would be nice if I could use a mongodb driver's connection URL syntax for connection and options...

example:

```
mongodb://username:password@server1,server2,server2/database?readPreference=nearest&maxPoolSize=500
```

**Comment by 97-109-107** [comment]
Should one be looking how to connect to a password protected mongo, I found this: http://stackoverflow.com/a/20812876/1064536

**Comment by tracker1** [comment]
@97-109-107 I know how to do just that... it's mainly that we keep our configuration in system environment variables, and it would be nice to use the same connection string for our scripts that use the mongodb node driver, as well as newer services that may use monk.... since mongodb has normalized around a connection uri string, it would be nice if this library also supported such a string.

**Comment by mathieudutour** [comment]
it is supported
