### ISSUE TITLE
Bulk API support

### ISSUE THREAD

**Issue by elyas-bhy** [Automattic/monk#85]
Is there any way to acheive proper [bulk insert](http://docs.mongodb.org/manual/reference/method/Bulk.insert/) in the current version of Monk? Supporting this feature would be quite useful, and having it return a promise which resolves after all items are added would be top-notch.

The only way I can do this right now is by iterating through my entries and inserting them one by one, which isn't efficient at all. It is even worse when I need to know when all entries are inserted before continuing.

**Comment by aliem** [comment]
You can use `Promise.all`, or chain promises:

```js
var promises = ary.map((c)=> db.insert({ foo: c }))
return Promise.all(promises)
```

```js
var promises = Promise.resolve()
ary.forEach((el)=> promises.then(db.insert({ foo: el })))

// resolve promises
promises.then ...
```

**Comment by elyas-bhy** [comment]
Your workaround handles the synchronization issue, but you are still inserting documents one at a time.
A more appropriate workaround would be to prepare the documents in an array, and inserting that array in one go.  

However, my question was more about whether there are any plans on supporting the Bulk API from mongodb in Monk.

**Comment by aliem** [comment]
My first snippet is actually an *unordered parallel poor-man* bulk insert.

I see the need of supporting the bulk API (was not aware that was part of mongodb). I guess mongoskin will have to implement it wrapping the mongo-native-driver [api](https://github.com/mongodb/node-mongodb-native/blob/fa57dc7a07cb46fbb4f0e167a60be0f3542a5e3e/test/functional/crud_api_tests.js#L365) (in a nicer way)

**Comment by Volox** [comment]
+1

**Comment by marcoancona** [comment]
+1

**Comment by mathieudutour** [comment]
You can insert an array of object

**Comment by elyas-bhy** [comment]
This issue was meant primarily for implementing the [Bulk API](https://docs.mongodb.com/manual/reference/method/js-bulk/) from mongodb, it's not just about inserting objects. Maybe the issue should be re-opened until this is discussed?

**Comment by mathieudutour** [comment]
I'm not really familiar with the Bulk API to be honest (but it looks very nice). Would you be able to work on it?

**Comment by elyas-bhy** [comment]
@mathieudutour I would love to but I already got my hands full of other projects already :confused:

**Comment by mathieudutour** [comment]
What would you say about implementing (`Collection.bulkWrite`)[http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#bulkWrite]? That would be a lot easier than the Bulk API you linked to.

**Comment by elyas-bhy** [comment]
@mathieudutour Looking through their source code, it seems that they are indeed relying on the Bulk API. However I'm not sure if they cover all possible operations.
Either way, I believe we can rely on `Collection.bulkWrite` since it is already provided by the native mongo driver.

**Comment by mathieudutour** [comment]
yes, probably better than nothing ;) We can always iterate later on

**Comment by elyas-bhy** [comment]
+1 :)
