### ISSUE TITLE
If a DB object is garbage collected, the connection should terminated?

### ISSUE THREAD

**Issue by hilts-vaughan** [Automattic/monk#89]
It seems like if a connection object is garbage collected, the connection will still live on. Consuming memory and network threads

**Comment by alFReD-NSH** [comment]
There's no way to detect that in Javascript. If you want to the connection to be closed, you should use the close method, for example:

```
var monk = require('monk');
var db = monk('localhost/test');
db.get('test').find({}, function (err, data) {
    // Do something with the data...
    // Now we are finished, we call the close method to close all connections.
    db.close();
});
