### ISSUE TITLE
Issue with mongoskin

### ISSUE THREAD

**Issue by DylanPiercey** [Automattic/monk#91]
```javascript
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^

TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/tacmarketing/WebstormProjects/tcomb-db/node_modules/monk/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/Users/tacmarketing/WebstormProjects/tcomb-db/node_modules/monk/node_modules/mongoskin/lib/admin.js:18:37)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```

Currently can't build monk and i'm not sure mongoskin will receive an update.

Are there any plans to remove mongoskin as a dependency?

Edit:

A temporary solution to fix this module would be to add mongodb@1.4.4 as a dependency as the issue stems from the fact that mongoskin switched (accidentially) to a peer dependency for mongodb@2.X which it does not support.

**Comment by lambtron** [comment]
Experiencing this same issue. Will use temporary fix.

**Comment by youngfreezy** [comment]
What exactly is the temporary fix? add that version of mongodb in the package.json for your app?

**Comment by DylanPiercey** [comment]
@youngfreezy yes.

**Comment by CapsE** [comment]
I get the exact same error but only when installing my server on heroku. Is there any progress in fixing this? I read here that there were ideas to remove mongoskin as a dependency.

**Comment by WilBeCoding** [comment]
That temp fix felt so good to implement. Thanks.

**Comment by vccabral** [comment]
I had the same issue but downgrading didn't work for me. I had to upgrade. In case someone has this problem too, here is the solution.

https://github.com/Automattic/monk/compare/master...vccabral:master

Then I edited my package.json

-    "monk": "^1.0.1",
+    "monk": "https://github.com/vccabral/monk.git",

**Comment by benjoshua** [comment]
Still can't get it to run on heroku. it's crashing my app right now and if I'm downgrading it gives me error when tring to get the db

any help?? Thanks!

**Comment by benjoshua** [comment]
@vccabral Thanks a lot!

**Comment by coloradude** [comment]
Suddenly getting the same error on an existing app

**Comment by WilBeCoding** [comment]
@coloradude Happened to me with Browser QB. Changing the version of MongoDB did the trick. Godspeed. Stay hydrated.

**Comment by daimajia** [comment]
+1 @coloradude

**Comment by daimajia** [comment]
@vccabral Thanks a lot, it works.

**Comment by JackWangz** [comment]
@vccabral It works for me, too. You save my day!

**Comment by alexdmiller** [comment]
@vccabral Maybe I don't understand the fix. I added those two lines to my package.json and then ran npm install. I'm still getting:

npm WARN EPEERINVALID mongoskin@2.0.3 requires a peer of mongodb@~2.0 but none was installed.

Also, isn't it a little silly that this bug has been open since March 23rd, 2015, and you still can't install monk? Is everyone who wants to use monk using this workaround?

**Comment by DylanPiercey** [comment]
@alexdmiller if you are using npm >= 3.0 you may have to remove your node_modules folder to ensure a proper version of mongoskin.

Also I don't think this library is well maintained and is missing some critical things like upgrading the underlying mongodb drivers and perhaps parting ways from mongoskin.

@rauchg @travisjeffery is this true? Does this library need more maintainers?

**Comment by jeremywadsack** [comment]
Ran into the same issue. Was able to fix with:

```
npm uninstall mongodb --save
npm install mongodb@1.4 --save
```

Which is what @DylanPiercey stated at the top.

I'm also concerned that this dependency issue has been open for 10 months.

**Comment by iposton** [comment]
@jeremywadsack solution fixed my problem deploying to heroku. Thanks.

**Comment by vccabral** [comment]
@alexdmiller I did not document all the steps but uninstalling mongob and installing a new version sounds familiar as well as this fork. @jeremywadsack thanks for the help.

**Comment by edguz2408** [comment]
Thanks @jeremywadsack, you just helped me solve my issue.

**Comment by WereMike** [comment]
Thanks @vccabral - though this seems crazy to have to do so far after the fact.
Maybe I should rethink using Monk on my new project.

**Comment by coloradude** [comment]
It's obviously an abandoned project. So silly.

**Comment by WereMike** [comment]
@coloradude I have come to the same conclusion. Just going straight MongoClient. There's little value in adding a little abstraction at the cost of weird hokey workarounds. Not for a greenfields project, anyhow.

**Comment by DylanPiercey** [comment]
@WereMike I have switched as well. Pretty easy with the current MongoClient returning promises. The only thing I missed was the auto casting of mongo IDs, but I just made my own super thin wrapper.

**Comment by pointnotfoe** [comment]
@jeremywadsack after trying that I get "npm WARN mongoskin@2.0.3 requires a peer of mongodb@~2.0 but none was installed."

if I change the dependency to 2.xx it reverts the error to 1.xx

**Comment by bneiluj** [comment]
To fix this issue, update your `package.json` to match: 

`  "dependencies": {
    "mongodb": "^1.4.40",
    "mongoskin": "1.3.20",
  }
`

remove all node modules: `rm -rf node_modules/`
and install everything back to update the node modules: `npm install`

**Comment by mathieudutour** [comment]
fixed in #132 🎉

**Comment by hktalent** [comment]
me too
$ npm install -g mongodb --save
/usr/local/lib
└─┬ mongodb@2.2.10 
  ├── es6-promise@3.2.1 
  ├─┬ mongodb-core@2.0.12 
  │ ├── bson@0.5.5 
  │ └─┬ require_optional@1.0.0 
  │   ├── resolve-from@2.0.0 
  │   └── semver@5.3.0 
  └─┬ readable-stream@2.1.5 
    ├── buffer-shims@1.0.0 
    ├── core-util-is@1.0.2 
    ├── inherits@2.0.3 
    ├── isarray@1.0.0 
    ├── process-nextick-args@1.0.7 
    ├── string_decoder@0.10.31 
    └── util-deprecate@1.0.2 

hktalent:nodeJs xiatian$ npm install -g mongoskin
/usr/local/lib
├── UNMET PEER DEPENDENCY mongodb@^2.0
└── mongoskin@2.1.0 

npm WARN mongoskin@2.1.0 requires a peer of mongodb@^2.0 but none was installed.

**Comment by schacker** [comment]
666，thx
