### ISSUE TITLE
MongoDB 2.0 Driver

### ISSUE THREAD

**Issue by anaibol** [Automattic/monk#93]
Are there plans to move to the new MongoDB 2.0 native driver for node? There are many new interesting things, insertOne(), .limit().skip(), etc..

**Comment by leecade** [comment]
:+1: look forward to monk2

> ref: https://www.mongodb.com/blog/post/introducing-nodejs-mongodb-20-driver

**Comment by travisjeffery** [comment]
yeah definitely, right now monk uses mongoskin which doesn't support 2.0 yet but we want to move away from using mongoskin anyway

**Comment by nickjackson** [comment]
Any word on this? Willing to help out.

**Comment by metame** [comment]
I would also be interested in contributing to supporting the 2.0 mongo driver.

**Comment by sean3z** [comment]
+1

**Comment by matobet** [comment]
:+1:

**Comment by paulshapiro** [comment]
+1

**Comment by metame** [comment]
Relevant to this thread, mongoskin 2.0 just came out that supports the 2.0 native driver.

**Comment by jgraham909** [comment]
+1

**Comment by narfdre** [comment]
+1

**Comment by IlyaMokin** [comment]
+1

**Comment by ratson** [comment]
Is monk2 still plan to move away from mongoskin? or update mongoskin to v2 (https://github.com/Automattic/monk/issues/111)?

**Comment by kuzyn** [comment]
:+1:

**Comment by lambtron** [comment]
+1

**Comment by kindalu** [comment]
+1

**Comment by realalexhomer** [comment]
+1

**Comment by TigerC10** [comment]
+1

**Comment by mathieudutour** [comment]
fixed in #132 🎉
