### ISSUE TITLE
how to use runCommand of mongodb

### ISSUE THREAD

**Issue by maqboolkhan** [Automattic/monk#98]
hi, 
monk is really cool but there is a problem that im working on a little search engine with mongodb and m doing text search so i have to run
`db.col.runCommand("text",{search:"gun", project: {"_id":0}});`
but i did not find any way to use it with `monk`
please help me that how to use it with monk
thanks

**Comment by metame** [comment]
_Old issue but in case someone else has this same issue._

To do a full text search using monk, pass the $text operand into the find query.  Doing a full text search requires a _text index_ on the field you want to search and there is only one _text index_ allowed per collection.

Example finding string 'foo' in collection 'posts'.

    db.get('posts').find({'$text': {'$search' : 'foo'}}, function(err, docs){
        // do something
    });
