### ISSUE TITLE
Promise for Empty/Null Query Results

### ISSUE THREAD

**Issue by woojoo666** [Automattic/monk#99]
Is there a promise for empty or null results, especially `collection.findOne`? I find it pretty counterintuitive to handle the null case inside the `success` handler, especially since the function is called `findOne`. Is there anything like

	collection.findOne({ key: value })
		.on('error', onErrorCallback)
		.on('null', onNoResultsCallback)
		.on('found', onUserCallback);

**Comment by travisjeffery** [comment]
Nope. It's nice too that the api is consistent with the callbacks api too IMO.
